WORKSPACE, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesService.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/15)
=> Update cross-media-measurement-api version.

.github/workflows/build-test.yml, .github/workflows/lint.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/35)
=> Trigger build-test and lint workflows on milestone0 branch.

src/test/cc/testutil/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/49)
=> Make the testutil library visible for public.

WORKSPACE, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/45)
=> Update cross-media-measurement-api version

src/main/proto/wfa/measurement/internal/loadtest/BUILD.bazel, src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43)
=> Add Correctness Test Labeled Event proto.

src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computation.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, src/main/proto/wfa/measurement/system/v1alpha/global_computation.proto, src/main/proto/wfa/measurement/system/v1alpha/global_computation_status_update.proto, src/main/proto/wfa/measurement/system/v1alpha/public_resource.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto
This is for #53.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/44)
=> Redefine system API resources to support v2alpha public API.

src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entries_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participants_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto, src/main/proto/wfa/measurement/system/v1alpha/global_computation_service.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition_service.proto, src/main/proto/wfa/measurement/system/v1alpha/requisitions_service.proto
Closes #53. This is intended to be merged into the main branch after the base PR #44 has been merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/55)
=> Redefine Kingdom system services to support v2alpha public API.

WORKSPACE, imports/java/com/google/cloud/bigquery/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessImpl.kt, src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessRunner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/57)
=> Read events data from BigQuery within CorrectnessTest.

src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computation/ComputationsService.kt, src/main/proto/wfa/measurement/internal/duchy/computations_service.proto
The changes are to support requisition related oeprations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/61)
=> Update duchy computationsService proto.

build/variables.bzl, src/main/k8s/BUILD.bazel, src/main/k8s/correctness_test_job.cue, src/main/k8s/duchy.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/Correctness.kt, src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessImpl.kt, src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessRunner.kt, src/test/kotlin/org/wfanet/measurement/loadtest/CorrectnessImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/73)
=> Generate sketches from bigquery data

WORKSPACE, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/CryptoKeySet.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/crypto.proto, src/main/proto/wfa/measurement/internal/kingdom/protocol_metadata.proto, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/BUILD.bazel, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/LiquidLegionsV2EncryptionUtilityTest.kt, src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/common/FakeDataProviderRule.kt
A kingdom internal ElGamalKey proto is also created, since the common
one in anysketch is not shared across repos any more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/70)
=> Update CMMS to use the latest version of the anysketch library.

src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/common/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/common/throttler/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/84)
=> Make common libraries visibility public

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabase.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitionsTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRequisitionTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisitionTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/83)
=> Stop stripping constraints when processing Spanner schema definitions.

src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationsServiceCoroutineStubs.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/89)
=> Implement updateRequisitionsAndKeySets() at the herald.

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt, src/test/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/gcloud/spanner/MutationsTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/100)
=> Add Kotlin domain-specific language (DSL) for Spanner mutations.

src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt, src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/common/ResourceNameParserTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/96)
=> Add ResourceNameParser class for parsing API resource names.

src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/104)
=> Update MPC noise generation to match the latest PoPETs paper.

src/main/kotlin/org/wfanet/measurement/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/system/v1alpha/ComputationKey.kt, src/main/kotlin/org/wfanet/measurement/system/v1alpha/ComputationLogEntryKey.kt, src/main/kotlin/org/wfanet/measurement/system/v1alpha/ComputationParticipantKey.kt, src/main/kotlin/org/wfanet/measurement/system/v1alpha/IdVariable.kt, src/main/kotlin/org/wfanet/measurement/system/v1alpha/RequisitionKey.kt, src/main/kotlin/org/wfanet/measurement/system/v1alpha/ResourceKey.kt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/99)
=> Add ResourceKey data classes for system API.

src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computation.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entries_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participants_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, src/main/proto/wfa/measurement/system/v1alpha/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/107)
=> Use resource names instead of Key messages in system API.

src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/108)
=> Minor update to make llv2_encryption_utility_test less flaky.

src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/112)
=> Fail the computation participant in case of PERMANENT errors.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/115)
=> Create kotlin skeleton classes for the four kingdom system serivces.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsService.kt, src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/117)
=> Implement the system requisitions service.

src/main/kotlin/org/wfanet/measurement/api/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/Version.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DuchyCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/MeasurementConsumerCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/config/public_api_protocol_configs.proto, src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, src/main/proto/wfa/measurement/system/v1alpha/computation.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/125)
=> Implement system API computationsService.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/129)
=> Implement system computationParticipantsService.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/132)
=> Implement system ComputationLogEntriesService.

src/main/docker/images.bzl, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ForwardedStorageRequisitionFulfillmentServer.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/RequisitionFulfillmentServer.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/server/GcsRequisitionFulfillmentServer.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/137)
=> Define requisitionFulfillment servers.

src/main/docker/images.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/SystemApiServer.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/138)
=> Define kingdom system api server.

.github/workflows/lint.yml, src/main/k8s/base.cue, src/main/k8s/correctness_test_job.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/130)
=> Fix correctness test for m0

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/141)
=> Add CreateExchange class to insert new Exchanges

WORKSPACE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/153)
=> Update common-jvm version

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/156)
=> Make parameters for kingdom internal services private

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttempt.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangeStepAttemptTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/152)
=> Add CreateExchangeStepAttempt class to insert new Attempts

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomApiServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/RequisitionServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/SystemApiServer.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/168)
=> Update the KingdomApiServer to support binding multiple services.

WORKSPACE, build/wfa/repositories.bzl, src/main/kotlin/org/wfanet/measurement/api/v2alpha/MeasurementConsumerKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Builder.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PreferredCertificates.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/166)
=> Implement v2alpha public API MeasurementConsumers service.

src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/exchange_workflow.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/174)
=> Add Internal Exchange Workflow proto

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt
This just adds the necessary files/classes. It does not yet implement
any logic -- the service implementation just returns a NotImplemented
error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/175)
=> Add internal SpannerRecurringExchangesService skeleton

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRecurringExchangesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/177)
=> Implement SpannerRecurringExchangesService.

WORKSPACE, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Certificates.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RecurringExchangesServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/data_provider.proto, src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt
This updates internal and v2alpha public service implementations to handle world-federation-of-advertisers/cross-media-measurement-api#37.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/179)
=> Update common-media-measurement-api to v0.2.0.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/185)
=> Avoid hasX() checks in proto oneofs in SpannerExchangeStepsService

WORKSPACE
Update WORKSPACE to be more dependent on common_jvm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/184)
=> Update WORKSPACE with common_jvm

WORKSPACE, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/InternalApiFlags.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomApiServer.kt, src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt, src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)
=> Create and implement the resource setup job.

build/repositories.bzl, src/main/docker/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_sketch_aggregation_v2.proto, src/main/proto/wfa/measurement/internal/duchy/requisition_details.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
https://rally1.rallydev.com/#/605340551071d/userstories?detail=%2Fuserstory%2F606022688385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/198)
=> Update the mill to enforce consent signaling checks.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/ForwardedStorageFrontendSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImpl.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/GcsFrontendSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/storage/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, src/test/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023913139
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/201)
=> Implement getResult and getEsitimatedResult in the FE simulator.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
Note that this does not yet include reading all appropriate fields for the COMPUTATION view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/207)
=> Set missing fields on internal Measurement.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/210)
=> Rename create_time field in internal Requisition to update_time.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/exchange.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, src/main/proto/wfa/measurement/internal/kingdom/macros.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/205)
=> Auto-fail expired ExchangeStepAttempts

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/testing/DuchyIdSetter.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/GetExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/SpannerQuery.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRecurringExchanges.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BaseSpannerReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/211)
=> Add internal SpannerRequisitionsService, implementing Get and Stream methods.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607712261053&fdp=true?fdp=true
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/225)
=> Fill missing fields for internal Measurement DEFAULT view.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607712261053&fdp=true?fdp=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/231)
=> Extract common ComputationParticipant building logic to ComputationParticipantReader.

src/main/docker/images.bzl, src/main/k8s/BUILD.bazel, src/main/k8s/configs/aggregator_protocols_setup_config.textproto, src/main/k8s/configs/duchy_id_config.textproto, src/main/k8s/configs/non_aggregator_protocols_setup_config.textproto, src/main/k8s/edp_simulator.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228900207
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/233)
=> Add cue config for edp_simulator.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/245)
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607707758715&fdp=true?fdp=true
=> Plumb Duchy certificate DER to system ComputationParticipant.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/241)
=> Implement Get Method for ExchangeStepAttempts service

src/main/k8s/certs/README.md, src/main/k8s/configs/duchy_rpc_config.textproto, src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, src/main/proto/wfa/measurement/config/duchy_rpc_config.proto
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607708919899&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/253)
=> Change the type of DuchyInfo.RootCertificateSkid to ByteString.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsServiceTest.kt
https://rally1.rallydev.com/#/604612930531d/tasks?detail=%2Ftask%2F607707408811&fdp=true?fdp=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/249)
=> Implement internal FulfillRequisition method.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/246)
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607707758715&fdp=true?fdp=true
=> Plumb DataProvider certificate DER to system Requisition.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/251)
=> Filter public Requisitions by parent Measurement state.

build/repositories.bzl, src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/257)
=> Update common-jvm and consent-signaling-client versions.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/260)
=> Set requisitionSpecHash in the system.Requisition.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/258)
https://rally1.rallydev.com/#/?detail=/task/607707408811&fdp=true
=> Add request validation to internal FulfillRequisition.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/259)
https://rally1.rallydev.com/#/?detail=/task/608697468821&fdp=true
=> Implement internal RefuseRequisition method.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt
This swaps Spanner code to use the newer/preferred overloads.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/262)
=> Update common-jvm to v0.10.0.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/main/proto/google/type/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, src/main/proto/wfa/measurement/internal/kingdom/exchange_steps_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/239)
=> Implement Get Method for ExchangeSteps service

src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt
https://rally1.rallydev.com/#/?detail=/task/608271743003&fdp=true
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/261)
=> Add PrincipalServerInterceptor to extract principals from X509 certs

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CancelMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/266)
https://rally1.rallydev.com/#/?detail=/task/608697561355&fdp=true
=> Implement internal CancelMeasurement method.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsServiceTest.kt
https://rally1.rallydev.com/#/604612930531d/portfolioitemstreegrid?detail=%2Ftask%2F607707755241&fdp=true?fdp=true
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/226)
=> Implement ConfirmComputationParticipant and FailComputationParticipant for internal spannerComputationParticipantService

src/main/k8s/edp_simulator.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/GcsEdpSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/265)
=> Update the cue config for the EdpSimulator.

build/repositories.bzl, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/269)
=> Update common-jvm to v0.11.0.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/268)
=> Set externalMeasurementId in requisitions stream filter

src/main/k8s/frontend_simulator.cue, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/272)
=> Compare the results within some tolerance since we have DP noises.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/273)
=> Fix minor bugs in the kingdom to pass the correctnessTest

build/repositories.bzl, src/main/k8s/duchy.cue, src/main/kotlin/org/wfanet/measurement/duchy/db/computation/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt, src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/ComputationControlService.kt, src/main/kotlin/org/wfanet/measurement/duchy/storage/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt, src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClientsTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactorTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/ComputationControlServiceTest.kt
Two major changes.
1. new computations are created at INITIALIZATION_PHASE stage instead of
CONFIRMATION_PHASE. No output blob is expected from this stage.
2. Updated the RequisitionStore and ComputationStore to use the Store
interface.
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F607228901955&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/271)
=> Fix the duchy for correctness test.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/275)
=> Only check the error type when the error exist in the log.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/278)
=> Do not populate providedId columns if they are empty

src/main/k8s/base.cue, src/main/k8s/frontend_simulator.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/resource_setup.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/279)
=> Add a job cue template.

src/main/k8s/configs/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/common/Configs.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt
This will be used in the inmemory IntegationTest. The current code is just
a best guess. We'll find whether it works or not when the actual test
code is written.
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609465361881&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/280)
=> Define the testRule for InProcessDuchy.

src/main/k8s/base.cue, src/main/k8s/duchy.cue
@wangyaopw @SanjayVas - looking for feedback if this is the right approach to add this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/282)
=> Add resource requests and limits to k8s pods

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609465361881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/286)
=> Update consent-signaling-client version.

src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt
Reverts world-federation-of-advertisers/cross-media-measurement#295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/297)
=> Revert "Create PanelMatchResourceSetup from Channel"

src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/298)
=> Create PanelMatchResourceSetup from Channels

.github/workflows/build-test.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/301)
=> Use floating v1 release of bazel-build-test GitHub Action.

src/main/k8s/base.cue, src/main/k8s/duchy.cue, src/main/k8s/kingdom.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue
- The duchy ones are missing the object-prefix.
- `from` and `podSelector` should be list object.
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F610324078661&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/299)
=> Update the network-config policy for kingdom and duchies.

src/main/k8s/base.cue, src/main/k8s/duchy.cue, src/main/k8s/edp_simulator.cue, src/main/k8s/kingdom.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F610324077415&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/303)
=> Switch to create Deployment instead of Pod for all services/daemons.

src/main/k8s/certs/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, src/test/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/common/Configs.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)
=> Add the InProcessEdpSimulator and integrationTestBase.

third_party/rbe_configs/cc/module.modulemap, third_party/rbe_configs/config/BUILD, tools/bazel-container, tools/gen-rbe-configs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/307)
=> Update containerized building to use latest Bazel image.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/gcloud/DuchyDependencyProviderRule.kt, src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt, src/test/kotlin/org/wfanet/measurement/integration/gcloud/KingdomDataServicesProviderRule.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/293)
=> Add the gcloud InProcessLifeOfAMeasurementIntegrationTest.

build/repositories.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/312)
=> Update common-jvm version.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RecurringExchangeReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/Providers.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelProvidersServiceTest.kt
https://rally1.rallydev.com/#/?detail=/defect/609066028953&fdp=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/310)
=> Clean up Exchange internal APIs

src/main/k8s/duchy.cue, src/main/k8s/edp_simulator.cue, src/main/k8s/frontend_simulator.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F610324081015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/321)
=> Change all external targets to object parameters in cue files.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/339)
=> Fix authentication in ClaimReadyExchangeStep.

src/main/k8s/base.cue, src/main/k8s/duchy.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/341)
=> Update pod resource request and limit to more reasonable values.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Assertion.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/342)
=> Enforce UTC time for dates in Spanner

src/main/k8s/kingdom.cue, src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto, src/main/k8s/testing/secretfiles/kustomization.yaml, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelProviderKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/TextprotoFilePrincipalLookup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaFlags.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Principal.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PrincipalServerInterceptor.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/main/proto/wfa/measurement/api/v2alpha/authority_key_to_principal_map.proto
https://rally1.rallydev.com/#/?detail=/userstory/613542239129&fdp=true
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/346)
=> Implement PrincipalLookup that reads from a textproto file

WORKSPACE, build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/345)
=> Update common-jvm to 0.20.0.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/349)
=> Set failure in public measurement.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ProviderFilter.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangeSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/exchange_steps_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/347)
=> Implement SpannerExchangeStepsService.streamExchangeSteps

build/repositories.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/352)
=> Update common-jvm to 0.21.1.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/AccountReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerOwnerReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateAccount.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/359)
=> Implement internal create account.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/api/v2alpha/ExchangeKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchangeSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Providers.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/exchange_steps_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/360)
=> Implement /ExchangeSteps.listExchangeSteps

src/main/k8s/base.cue, src/main/k8s/dev/duchy_gke.cue, src/main/k8s/dev/edp_simulator_gke.cue, src/main/k8s/dev/kingdom_gke.cue, src/main/k8s/duchy.cue, src/main/k8s/edp_simulator.cue, src/main/k8s/kingdom.cue, src/main/k8s/kingdom_and_three_duchies_gke.cue, src/main/k8s/kingdom_and_three_duchies_local.cue
The default value is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/358)
=> Require cue files to explicitly configure the resource requirement of all deployments.

third_party/rbe_configs/config/BUILD, tools/bazel-container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/361)
=> Update Bazel container image to latest.

build/repositories.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/365)
=> Bump dependency versions

src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt
The spanner emulator has transicent errors not caught in the integration
test, which kills the mill. This PR would prevent such transient/retriable
errors from crashing the mill and breaking the
GCloudInProcessLifeOfAMeasurementIntegrationTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/364)
=> Suppress all exceptions in the mill loop processing.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/368)
=> Prevent setting of participant requisition params with invalid duchy certificate

src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F614639457875&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/369)
=> Fail the computation at the mill if the #attempt exceeds the limit.

src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/370)
=> Set exponential backoff between reties of the mills.

.editorconfig, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/integration/PanelMatchResourceSetup.kt
https://rally1.rallydev.com/#/?detail=/userstory/608698956441&fdp=true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/371)
=> Add CreateResource binary for making EDPs, MPs, RecurringExchanges.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/375)
=> Clarify authz in FinishExchangeStepAttempt

src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/RequisitionFulfillmentServer.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F615173529171&view=2c2927c0-626b-4740-8620-af2a93b7d623
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/377)
=> Check EDP authorization in the duchy RequisitionFulfillmentService.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/MakeProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/367)
=> Fix parsing provider from request

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/381)
=> Fix bug in ExchangeStepReader

src/main/k8s/duchy.cue, src/main/k8s/testing/secretfiles/authority_key_identifier_to_principal_map.textproto
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F615173529171&view=2c2927c0-626b-4740-8620-af2a93b7d623
Tested on GKE.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/379)
=> Update cue file to enable EDP authorization at the duchies.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Assertion.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/382)
=> Fix bug in findReadyExchangeSteps

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/383)
=> Reduce chattiness of Spanner transaction logging

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/385)
=> Fix bug in FinishExchangeStepAttempt

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/376)
=> Implement public authenticate.

src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationParticipantsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/386)
=> Check duchy identity in the kingdom system API.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)
=> Change format of event group page token.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, src/main/proto/wfa/measurement/internal/kingdom/api_key.proto, src/main/proto/wfa/measurement/internal/kingdom/api_keys_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/387)
=> Add internal api keys protos and schema changes.

src/main/proto/wfa/measurement/internal/kingdom/event_group.proto, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/388)
=> Update internal API for Event Groups.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/OpenIdConnectIdentityReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ActivateAccount.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/395)
=> Implement internal activate account.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/proto/wfa/measurement/internal/kingdom/measurement_consumers_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/394)
=> Implement public add and remove measurement consumer owners.

src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt, src/main/kotlin/org/wfanet/measurement/tools/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/measurement_consumer.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/397)
=> Modify public create measurement consumer to require creation token.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/OpenIdConnectIdentityReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceAccountIdentityWithNewOpenIdConnectIdentity.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/398)
=> Implement internal replace account identity.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/399)
=> Change format of next page token for requisitions service.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/402)
=> Update the continuationToken used in the system computationsService

src/main/proto/wfa/any_sketch/BUILD.bazel, src/main/proto/wfa/any_sketch/crypto/BUILD.bazel, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/main/proto/wfa/measurement/config/BUILD.bazel, src/main/proto/wfa/measurement/internal/common/BUILD.bazel, src/main/proto/wfa/measurement/internal/duchy/BUILD.bazel, src/main/proto/wfa/measurement/internal/duchy/config/BUILD.bazel, src/main/proto/wfa/measurement/internal/duchy/protocol/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/macros.bzl, src/main/proto/wfa/measurement/internal/loadtest/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/407)
=> Update Bazel loads to use new locations

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/412)
=> Update EventGroupReader to return EventGroupId

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)
=> Update spanner eventgroups

src/main/k8s/base.cue, src/main/k8s/kingdom.cue, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt
Added an interceptor in the Kingdom Internal AccountsService to make it
work. We should consider putting the token_id inside the request instead
of in the side channel for internal RPCs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/414)
=> Fix the dev deployment on GKE.

build/cue/defs.bzl, build/variables.bzl, docs/building.md, src/main/docker/BUILD.bazel, src/main/k8s/BUILD.bazel, src/main/k8s/macros.bzl
This allows these values to be specified on the Bazel command-line. Per-run configuration should never be under version control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/410)
=> Use Make variable strings in build/variables.bzl.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerComputationParticipantsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)
=> Implement internal UpdateEventGroup

tools/bazel-container, tools/bazel-container-run
This also adds a tools/bazel-container-run script for convenience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/423)
=> Update tools/bazel-container script to copy ~/.bazelrc into container.

build/repositories.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/424)
=> Update common-jvm from v0.27.0-rc1 to v0.27.0.

docs/gke/correctness-test.md, docs/gke/duchy-deployment.md, docs/gke/kingdom-deployment.md
The contents are the same as the corresponding google docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/433)
=> Add github docs for kingdom/duchy deployment.

WORKSPACE, src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/eventDataProvider/privacyBudgetManagement/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/440)
=> Add folder structure for EventFiltration and PrivacyBudgetManager + cel-java dependency

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/446)
=> Switch to internal api in integration test for duchy certificate creation.

docs/operations/README.md, docs/operations/creating-resources.md, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/442)
=> Add operations guide for creating resources in the Kingdom.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventField.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt, src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto, src/test/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventFieldTest.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/445)
=> Create EventTemplate and EventField data classes

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/452)
=> Allow ModelProvider to get DataProviders certificate

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/448)
=> Specify next exchange date when creating RecurringExchange.

src/main/k8s/local/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/454)
=> Add mc_api_key option to Deploy MC Frontend Simulator section of local KIND README.

docs/gke/cluster-config.md, docs/gke/correctness-test.md, docs/gke/kingdom-deployment.md, src/main/k8s/base.cue, src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/base_gke.cue, src/main/k8s/dev/kingdom_gke.cue, src/main/k8s/duchy.cue, src/main/k8s/kingdom.cue, src/main/k8s/local/kingdom.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/455)
=> Use Workload Identity for dev GKE Kingdom.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/463)
=> Fix cronSchedule not being set when creating RecurringExchange.

src/main/k8s/local/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/460)
=> Fix incorrect image for local EDP simulator configuration.

src/main/k8s/base.cue, src/main/k8s/dev/resource_setup_gke.cue, src/main/k8s/resource_setup.cue
The individual resource creation is not repeatable due to certificate uniqueness, so if there's a partial failure then the records need to be wiped from the DB before it can be run again.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/449)
=> Never restart Kingdom resource setup job.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md
This makes it clearer that these flags are common rather than specific to a given subcommand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/459)
=> Move API and TLS flags to parent CreateResource command.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EncryptionPublicKeys.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/462)
=> Add EncryptionPublicKeys command-line util.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/465)
=> Set measurement failure reason for requisition refused and computation participant failure.

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/474)
=> Call EdpSimulator code for sampling VIDs

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/497)
=> Fix handling of empty protocol config.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/ComputationControlService.kt, src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt, src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/storage/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClientsTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/ComputationControlServiceTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt
This updates common-jvm to 0.32.0.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/476)
https://rally1.rallydev.com/#/?detail=/task/625602588885&fdp=true
=> Use deterministic blob keys for blob storage.

src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/InternalApiFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetupFlags.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/484)
=> Clarify cert-host flags, making them optional.

.bazelrc, WORKSPACE, docs/building.md, tools/bazel-container
Fixes #494.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/499)
=> Support running TestContainers-based tests in our build container.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorRunner.kt, src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computation.proto, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt
This updates cross-media-measurement-api to 0.20.0 and common-jvm to 0.31.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/501)
=> Change the Measurement.aggregator_certificate field to a resource name.

src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/514)
=> Remove occurrences of fingerprint from public requisitions service.

src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapperTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/523)
=> Privacy Bucket Mapper Implementation

build/repositories.bzl, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/model_provider.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/540)
=> Remove unused dependencies for ModelProvider

src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedCompositionTest.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/541)
=> Small update to Binom to persistently cache coefficients and support concurrency.

src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/CompositionTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/557)
=> Clean up Ledger Code

src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/550)
=> Use library targets rather than lists to group common integration test deps.

src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto, src/main/proto/wfa/measurement/reporting/v1alpha/reporting_set.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/566)
=> Fix Metric.SetOperation.reporting_set to be a resource reference.

src/main/kotlin/org/wfanet/measurement/loadtest/config/PrivacyBudgets.kt, src/main/proto/wfa/measurement/loadtest/config/BUILD.bazel, src/main/proto/wfa/measurement/loadtest/config/loadtest_event.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/572)
=> Event Field fix for EDPSimulatorRunner

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/573)
=> Raise error when updating CertificateRevocationState from REVOKED to HOLD

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupMetadataDescriptorsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroupMetadataDescriptors.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupMetadataDescriptorsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptors_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/580)
=> Remove filtering and pagination features unnecessary for BatchGet

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/README.md, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/Certificates.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/577)
=> Add duchy-certificate subcommand to CreateResource.

src/main/kotlin/org/wfanet/measurement/api/ApiKeyConstants.kt, src/main/kotlin/org/wfanet/measurement/api/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt, src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeyAuthenticationServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/594)
=> Add API key for SimpleReport

src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/CompositionTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/576)
=> Update advanced composition code to avoid a numeric overflow.

src/main/k8s/resource_setup.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/505)
=> Fix resource setup job not respecting service dependencies.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementFailure.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/614)
=> Bump common-jvm to 0.38.0

src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReportTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/609)
=> Add page navigation for SimpleReport list command

src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt
[#636](https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/636)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/638)
=> Add Privacy Bucket Filter test proving leaving out a field in the filter works fine

src/main/k8s/base.cue, src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/base_gke.cue, src/main/k8s/dev/duchy_gke.cue, src/main/k8s/dev/edp_simulator_gke.cue, src/main/k8s/dev/frontend_simulator_gke.cue, src/main/k8s/dev/kingdom_gke.cue, src/main/k8s/dev/panel_match_resource_setup_gke.cue, src/main/k8s/dev/resource_setup_gke.cue, src/main/k8s/duchy.cue, src/main/k8s/edp_simulator.cue, src/main/k8s/frontend_simulator.cue, src/main/k8s/kingdom.cue, src/main/k8s/local/BUILD.bazel, src/main/k8s/local/config.cue, src/main/k8s/local/duchies.cue, src/main/k8s/local/edp_simulators.cue, src/main/k8s/local/emulators.cue, src/main/k8s/local/frontend_simulator.cue, src/main/k8s/local/kingdom.cue, src/main/k8s/local/resource_setup.cue, src/main/k8s/panel_match_resource_setup.cue, src/main/k8s/resource_setup.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/610)
=> Ensure Java-based pods have JVM memory options specified.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/637)
=> Update private key injection with EncryptionKeyPairStore

src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
This follows the more common practice of having a function either be suspending or return with background coroutines still running, but not both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/586)
=> Suspend start/update until all retries are complete.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
Fix the wrong assumption that the signing private key in the reporting server is paired with the certificate in the measurement consumer resource. This PR adds a private data class, `SigningConfig`, to `ReportsService` and use the signing certificate to create a measurement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/642)
=> Use signing certificate instead of measurement consumer certificate when creating measurement

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/648)
=> Add ListEventGroups command to reporting CLI

src/main/k8s/local/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/647)
=> Update ConfigMap example in the Local Kubernetes Deployment documentation

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQuery.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/GcsEdpSimulatorRunner.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/FilterEventQueryTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/641)
=> Move FilterEventQuery into own class

src/main/resources/duchy/spanner/changelog.yaml, src/main/resources/duchy/spanner/create-computations-schema.sql, src/main/resources/kingdom/spanner/changelog.yaml, src/main/resources/kingdom/spanner/create-exchange-schema.sql, src/main/resources/kingdom/spanner/create-measurement-schema.sql
This avoids synchronization delays between individual DDL transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/629)
=> Batch DDL statements for Spanner schema creation.

WORKSPACE, imports/java/com/opentable/db/postgres/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/postgres/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/reporting/deploy/postgres/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/653)
=> Remove conflicting embedded postgres import

docs/gke/cluster-config.md, docs/gke/duchy-deployment.md, docs/gke/kingdom-deployment.md, docs/gke/reporting-server-deployment.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/651)
=> Write GKE deployment guide for Reporting server.

build/repositories.bzl, src/main/k8s/testing/secretfiles/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/634)
=> Add measurement-consumers create command to MeasurementSystem CLI.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/654)
=> Fix examples for Reporting CLI.

src/main/k8s/duchy.cue, src/main/k8s/kingdom.cue, src/main/k8s/reporting.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/660)
=> Fix option name of healthPort

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/662)
=> Update report reader to include measurements.

src/main/kotlin/org/wfanet/measurement/eventdataprovider/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/665)
=> Add readme for Event Data Provider folder

build/repositories.bzl, src/main/k8s/postgres.cue, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/666)
=> Bump to common-jvm 0.43.2. Use CommandLineTesting for CLI test

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PublicKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/664)
=> Convert uncaught Exceptions to StatusException

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupParentKey.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/668)
=> Adjust parent test field in reporting server EventGroupsServiceTest

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RandomEventQuery.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)
=> Compute direct reach and frequency in EDP simulator

docs/gke/cluster-config.md, docs/gke/correctness-test.md, src/main/k8s/dev/config.cue, src/main/k8s/dev/edp_simulator_gke.cue, src/main/k8s/dev/frontend_simulator_gke.cue, src/main/k8s/edp_simulator.cue, src/main/k8s/frontend_simulator.cue, src/main/k8s/local/config.cue, src/main/k8s/local/edp_simulators.cue, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/GcsEdpSimulatorRunner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/661)
=> Use Workload Identity for EDP simulators on GKE.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/SetOperationCompiler.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/681)
=> Prevent concurrent modification error.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/README.md, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/ReportingTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/682)
=> Add --idempotency-key to Reporting CLI

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PublicKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/684)
=> Catch StatusException instead of StatusRuntimeException

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/683)
=> Scale direct reach value by sampling rate in EDP simulator

src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/689)
=> Add max_frequency_per_user to reachAndFrequency type in CLI

src/main/k8s/base.cue, src/main/k8s/duchy.cue, src/main/k8s/kingdom.cue, src/main/k8s/reporting.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/686)
=> Support emptyDir volume mounts.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/691)
=> Update delta value in examples of README

src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/699)
=> Refine logs of herald and mill

src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt
Mill always has logs at the beginning of running. It is because the ComputationServer pods usually take longer to get ready. This PR is to catch these errors and log at INFO level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/701)
=> Catch UNAVAILABLE exception when ComputationServer not ready

build/repositories.bzl, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BenchmarkTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/704)
=> Update common-jvm to 0.46.0.

build/variables.bzl, docs/gke/correctness-test.md, docs/gke/duchy-deployment.md, docs/gke/kingdom-deployment.md, docs/gke/reporting-server-deployment.md, src/main/docker/BUILD.bazel, src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/config.cue
This variable applies to both container push as well as the K8s configuration for the dev environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/706)
=> Specify Make variable for image tag.

docs/gke/correctness-test.md, docs/gke/duchy-deployment.md, docs/gke/kingdom-deployment.md, docs/operations/creating-resources.md, src/main/k8s/local/README.md, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/Output.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt, src/main/proto/wfa/measurement/loadtest/resourcesetup/BUILD.bazel, src/main/proto/wfa/measurement/loadtest/resourcesetup/resources.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/694)
=> Output machine-readable data from ResourceSetup.

src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/panel_match_resource_setup_gke.cue, src/main/k8s/panel_match_resource_setup.cue, src/main/kotlin/org/wfanet/measurement/api/v2alpha/IdVariable.kt, src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetup.kt, src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetupFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetupRunner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/709)
=> Fix Kotlin warnings, removing unused code.

src/main/k8s/dev/kingdom_gke.cue, src/main/k8s/duchy.cue, src/main/k8s/kingdom.cue, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto
This prevents said RPCs from overloading the Kingdom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/697)
=> Improve handling of long-lived streaming RPCs.

.github/workflows/build-test.yml, src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorRunner.kt, src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel
* Adjust logging.
* Wait for event group creation rather than polling.
* Use shorter result polling delay.
* Clean up background job start/stop.
* Specify individual test method timeouts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/707)
=> Improve debuggability of integration test.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerApiKeysService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeyAuthenticationServerInterceptor.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/AccountsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ApiKeysServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/708)
=> Use SuspendableServerInterceptor for auth interceptors.

src/main/k8s/kingdom.cue, src/main/k8s/testing/secretfiles/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/430)
=> Ensure Kingdom internal server only trusts Kingdom certs.

src/main/k8s/dev/prometheus_gke.cue, src/main/k8s/local/prometheus.cue, src/main/k8s/open_telemetry.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/732)
=> Add prometheus recording rules.

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/InternalApiFlags.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/Utils.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/711)
=> Specify a default deadline on RPCs to Kingdom internal server.

src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/ServiceFlags.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/AsyncComputationControlServer.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/RequisitionFulfillmentServer.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/713)
=> Specify a default deadline on RPCs to Duchy internal Computations server.

src/main/k8s/base.cue
This relies on the fact that emptyDir mount contents persist until the pod gets moved to another node.
Note that until `kubectl debug` supports adding volume mounts, one would have to use the K8s API to create an ephemeral container with the `tar` binary such that `kubectl cp` can be used to grab the dump from the emptyDir volume. See https://iximiuz.com/en/posts/kubernetes-ephemeral-containers/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/724)
=> Configure all Deployments to heap dump on Java OOM.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt
https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/739
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/740)
=> Add default value for filter in Reporting CLI

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/741)
=> Remove parallelization of Reporting Server Postgres queries.

docs/gke/metrics-deployment.md, src/main/k8s/base.cue, src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/base_gke.cue, src/main/k8s/dev/open_telemetry_gke.cue, src/main/k8s/dev/open_telemetry_gke_spanner.cue, src/main/k8s/dev/prometheus_gke.cue, src/main/k8s/local/open_telemetry.cue, src/main/k8s/open_telemetry.cue
This splits up build targets for Spanner collection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/747)
=> Reorganize metrics deployment guide for GKE.

docs/gke/metrics-deployment.md, src/main/k8s/base.cue, src/main/k8s/dev/open_telemetry_gke.cue, src/main/k8s/dev/open_telemetry_gke_spanner.cue, src/main/k8s/dev/prometheus_gke.cue, src/main/k8s/duchy.cue, src/main/k8s/grafana.cue, src/main/k8s/kingdom.cue, src/main/k8s/open_telemetry.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/751)
=> Switch to a single deployment from sidecar opentelemetry collectors.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/771)
=> Reporting list event group now correctly calls kingdom list event groups

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/770)
=> Fix retrieval of report measurements when getting a report.

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/776)
=> Fix the format of the column header in report.

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/791)
=> Fix creation of measurementCalculations in public reports service

src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/SetMeasurementResult.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/793)
=> Add padding to reporting frequency result values list.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/795)
=> Fix reporting tool periodic increment

.github/workflows/build-test.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/807)
=> Temporarily disable correctness test in Build and test workflow.

src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/811)
=> Add document on the metric parameters

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/817)
=> Fix EventGroupReader Retrieval of ExternalMeasurementConsumerCertificateId

src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/815)
=> Add proto for eventGroup delete

src/main/k8s/local/BUILD.bazel, src/main/k8s/local/emulators.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/834)
Fixes #833
=> Pin Spanner emulator container version.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/822)
=> Implement delete api for event group service

src/main/kotlin/org/wfanet/measurement/common/k8s/testing/PortForwarder.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, src/test/kotlin/org/wfanet/measurement/integration/k8s/CorrectnessTest.kt
This ensures that if cluser initialization hangs, we can still get cluster logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/832)
=> Add timeout to cluster initialization in correctness test.

src/test/kotlin/org/wfanet/measurement/integration/postgres/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/828)
See #827
=> Mark PostgresInProcessLifeOfAReportIntegrationTest as flaky.

docs/code-style.md, docs/dev-standards.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/829)
=> Deduplicate and clarify documentation on code style.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/825)
Fixes #823 
https://rally1.rallydev.com/#/?detail=/defect/683915011429&fdp=true
=> Verify DataProvider public key signature when creating Measurements for Report

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt
This is to reduce the number of table rows scanned. Spanner Query Insights on QA showed an average latency of ~300ms and average rows scanned of ~4162.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/847)
=> Rearrange joins on ComputationParticipantReader.

docs/gke/cluster-config.md, docs/gke/correctness-test.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/821)
=> Fix deployment docs w.r.t. BigQuery.

.clang-format, build/repositories.bzl, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/BUILD.bazel, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc
For the changes in any-sketch PR https://github.com/world-federation-of-advertisers/any-sketch/pull/20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/846)
=> Refactor GetDistributedGeometricRandomComponent function to DistributedGeometricNoiser class.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt, src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt
Add default value for requiredDuchies option
=> add default value for non-required option

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)
=> Implementation of Internal spanner eventgroup deletion

src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)
=> v2alpha database schema

src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto
Defined methods using Google API guidance  https://google.aip.dev/235  and https://google.aip.dev/234
=> Define batch delete and cancel api for measurements

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/AbstractNoiser.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/GaussianNoiser.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/LaplaceNoiser.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/Noiser.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/GaussianNoiserTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/LaplaceNoiserTest.kt
And created a Noiser interface for Laplace and Gaussian Noisers
=> Create Gaussian Noiser in EDP simulator for direct measurements

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt, src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt, src/test/kotlin/org/wfanet/measurement/integration/common/kingdom/service/api/v2alpha/FakeMeasurementsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
Implement reach-only measurements without breaking the current usage in upstream services.
=> Implement reach measurement type

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt
BigQuery timestamps are represented as microseconds since epoch.
=> Fix BigQuery timestamp conversions.

src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
[synthetic-labelled-events.csv](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/testing/data/synthetic-labelled-events.csv) only contains events in the date range [2021-03-04, 2021-03-28].
=> Use date range which exists in test data CSV

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto
=> Provide default value for unspecified NoiseMechanism for old Measurements

.github/workflows/configure-simulators.yml, .github/workflows/update-cmms.yml
https://rally1.rallydev.com/#/?detail=/task/700460294935&fdp=true
=> Deploy EDP simulators to dev environment on release.

src/main/terraform/gcloud/cmms/README.md, src/main/terraform/gcloud/cmms/main.tf, src/main/terraform/gcloud/cmms/reporting.tf, src/main/terraform/gcloud/cmms/variables.tf, src/main/terraform/gcloud/modules/reporting/README.md, src/main/terraform/gcloud/modules/reporting/main.tf, src/main/terraform/gcloud/modules/reporting/variables.tf, src/main/terraform/gcloud/modules/reporting/versions.tf
https://rally1.rallydev.com/#/?detail=/task/700460305079&fdp=true
=> Add Terraform config for Reporting system.

src/main/terraform/gcloud/cmms/duchies.tf, src/main/terraform/gcloud/cmms/main.tf, src/main/terraform/gcloud/cmms/reporting.tf, src/main/terraform/gcloud/cmms/simulators.tf, src/main/terraform/gcloud/cmms/variables.tf, src/main/terraform/gcloud/modules/simulators/README.md, src/main/terraform/gcloud/modules/simulators/main.tf, src/main/terraform/gcloud/modules/simulators/variables.tf, src/main/terraform/gcloud/modules/simulators/versions.tf
https://rally1.rallydev.com/#/?detail=/task/700460304467&fdp=true
=> Add Terraform config for EDP simulators.

.github/workflows/configure-duchy.yml, .github/workflows/configure-kingdom.yml, .github/workflows/configure-reporting.yml, .github/workflows/configure-simulators.yml, .github/workflows/run-k8s-tests.yml, .github/workflows/update-cmms.yml
https://rally1.rallydev.com/#/?detail=/task/700459544421&fdp=true
=> Run correctness test as part of update workflow.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ActivateAccount.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateApiKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroupMetadataDescriptor.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteApiKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, src/main/resources/kingdom/spanner/add-create-request-ids.sql, src/main/resources/kingdom/spanner/changelog.yaml, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
This is a breaking change to both the public CMMS API and the internal Kingdom API.
=> Update cross-media-measurement-api to 0.31.0.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelShardsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelShards.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelShardReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelShard.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteModelShard.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelShardsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, src/main/proto/wfa/measurement/internal/kingdom/model_shard.proto, src/main/proto/wfa/measurement/internal/kingdom/model_shards_service.proto, src/main/resources/kingdom/spanner/add-model-release-unique-index.sql, src/main/resources/kingdom/spanner/changelog.yaml, src/main/resources/kingdom/spanner/update-model-shards-foreign-key.sql, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelShardsServiceTest.kt
This is the last PR for internal APIs related to VID Model distribution
=> create model shard spanner service

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
=> Using CMMS event group key for CMMS event groups.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/Benchmark.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
This is a breaking change to the public API for CreateMeasurement.
https://rally1.rallydev.com/#/?detail=/task/702042750337&fdp=true
=> Update cross-media-measurement-api to v0.33.0.

src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/GaussianNoiser.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
* Add NONE directNoiseMechanism for testing purpose
* Change direct measurement noise mechanism name to `directNoiseMechanism` to differentiate from MPC `noiseMechanism`
* Some improvements to GaussianNoiser
=> Add NONE DirectNoiseMechanism.

.github/workflows/push-images.yml
This fixes a workflow bug introduced in #1079
=> Fix image-tag workflow output.

.github/workflows/api-lint.yml, src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SetContinuationToken.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/postgres/writers/SetContinutationToken.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ContinuationTokensServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computation.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_control_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entries_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto, src/main/proto/wfa/measurement/system/v1alpha/computation_participants_service.proto, src/main/proto/wfa/measurement/system/v1alpha/computations_service.proto, src/main/proto/wfa/measurement/system/v1alpha/differential_privacy.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, src/main/proto/wfa/measurement/system/v1alpha/requisitions_service.proto, src/main/proto/wfa/measurement/system/v1alpha/stage_attempt.proto, src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt
This includes a breaking change to the Kingdom internal API to address inconsistencies in StreamMeasurements filtration.
=> Fix api-linter errors in system API.

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGenerationTest.kt
* Take in a single SyntheticEventGroupSpec.
* Output labeled events with VIDs and timestamps.
=> Fix SyntheticDataGeneration signature.

src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
This also fixes test event filters in the Reporting integration test for #1094.
=> Fix CEL syntax for Reporting filter conjunctions.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/EventTemplateValidator.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md, src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel, src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/bad_templates.proto, src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/EventTemplateValidatorTest.kt
This also drops the UK Pilot event templates from this repository.
Closes #1168
=> Add CLI tool for validating event templates.

docs/operations/updating-release.md
https://rally1.rallydev.com/#/?detail=/task/720940466317&fdp=true
=> Add a guide for updating to a new Halo release.

experimental/reporting-ui/src/main/react/reporting-ui/jest.config.js
Didn't update a `require` path when moving files around. Fixing this so the react tests pass.
=> Fix broken jest tests.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PublicKeysServiceTest.kt
=> Fix internal UpdatePublicKey to write PublicKeyCertificateId.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PublicKeysServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/SequentialIdGenerator.kt
=> Fix internal GetDataProvider possibly returning incorrect Certificate.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/CertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DuchyCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/DuchyKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/MeasurementConsumerCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/MeasurementConsumerKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelProviderCertificateKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelProviderKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt
This is pre-factoring for implementing ListCertificates.
=> Simplify Certificate key parsing and auth using sealed interfaces.

build/repositories.bzl, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamCertificates.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt
Updates the cross-media-measurement-api dependency to 0.42.0.
=> Update cross-media-measurement-api dep for ListCertificates.

src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt, src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
* Add VariancesInterface for its user services easier testing.
* Set methodology-specific variance calculation functions private.
=> Add VariancesInterface

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/service/DataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/PopulationReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreatePopulation.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsServiceTest.kt
- Creates SpannerPopulationsService
- Implements Create, Get, And Stream methods
- Creates tests
=> Implement internal Populations service.

.github/workflows/api-lint.yml, .github/workflows/build-test.yml, .github/workflows/lint.yml, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc, src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/reach_only_liquid_legions_v2_encryption_utility.cc, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto, src/main/proto/wfa/measurement/internal/duchy/protocol/reach_only_liquid_legions_v2_encryption_methods.proto, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc, src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/reach_only_liquid_legions_v2_encryption_utility_test.cc, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/LiquidLegionsV2EncryptionUtilityTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/ReachOnlyLiquidLegionsV2EncryptionUtilityTest.kt
This contains no manual edits to any of the cherry-picked commits.
=> Cherry-pick fixes to 0.4.x

docs/operations/certificate-key-rotation.md, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md
=> Add a guide covering leaf certificate and encryption key rotation.

src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt, src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt, src/main/proto/wfa/measurement/internal/reporting/v2/report.proto, src/main/resources/reporting/postgres/add-details-column-to-reports.sql, src/main/resources/reporting/postgres/changelog-v2.yaml, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
This PR implements the tags field which was added to `Report` in #1251. A change to the DB schema is needed.
=> Add report tags

.github/workflows/build-test.yml, src/main/k8s/dev/edp_simulator_gke.cue, src/main/k8s/edp_simulator.cue
This also updates pre-merge checks to ensure that the target can build successfully.
=> Fix generation of BigQuery EDP simulator K8s configs.

.github/actions/configure-metrics-aws/action.yml, .github/actions/configure-metrics/action.yml, WORKSPACE, build/repositories.bzl, build/versions.bzl, docs/gke/metrics-deployment.md, imports/java/io/opentelemetry/api/BUILD.bazel, imports/java/io/opentelemetry/semconv/BUILD.bazel, src/main/k8s/local/README.md, src/main/k8s/open_telemetry.cue, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt, src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/batch/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/ExchangesDeletionJob.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/PendingMeasurementsCancellationJob.kt, src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel
=> Update common-jvm for trace ID logging.

experimental/reporting-ui/docs/gke/demo-ui-deployment.md, experimental/reporting-ui/src/main/k8s/dev/reporting_ui.yaml
Adding deployment script for the Demo UI and fully comprehensive directions.
=> Create Demo-UI Deploy Scripts and Directions

experimental/reporting-ui/src/main/go/org/wfanet/measurement/reporting/bff/gateway/runServer.go, experimental/reporting-ui/src/main/react/reporting-ui/client/reporting/client_impl.ts, experimental/reporting-ui/src/main/react/reporting-ui/index.tsx, experimental/reporting-ui/src/main/react/reporting-ui/model/reporting/init_api_props.ts
Changes:
* Remove the client requirements for TLS to connect to the GRPC-Gateway.
* Finished adding the API calls in the UI, fixing some of them.
* Added connection from UI to BFF, but the BFF isn't deployed yet, so will update the URL when it is. Unfortunately can't pass as a command line parameter or environment variable.
=> Connecting Reporting UI to BFF

src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt, src/main/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/AdvanceComputationRequestHeaders.kt, src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto, src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesDetailsTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocolEnumStagesTest.kt, src/test/kotlin/org/wfanet/measurement/duchy/service/system/v1alpha/ComputationControlServiceTest.kt
WAIT_ON_INPUT stage is changed into WAIT_ON_SHUFFLE_INPUT or WAIT_ON_AGGREGATION_INPUT
Thus, for non-aggregators, the normal stage transition is:
INITIALIZED -> SETUP_PHASE -> **(WAIT_ON_SHUFFLE_INPUT)** -> SHUFFLE_PHASE-> COMPLETE
(Note, WAIT_ON_SHUFFLE_INPUT could be skipped.)
For the aggregator, the normal stage transition is:
**WAIT_ON_AGGREGATION_INPUT** -> AGGREGATION_PHASE -> COMPLETE
=> HMSS splits WAIT_ON_INPUT into two types of stages.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt
cherrypick the change onto a 0.4.x fix branch
=> Jmolle cherrypick task api fix

src/main/k8s/panelmatch/dev/example_daemon_aws.cue, src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt, src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt, src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt, src/test/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClientTest.kt
Reverts world-federation-of-advertisers/cross-media-measurement#1386
=> Revert "Exchangestep Claiming limiting and exportTask fix"

src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt, src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt
- This S3 issue returned due to a regression.
I'll submit this without review if I don't get feedback before EOD my time, it is already in main and a minor change.
=> Cherrypick PR#1240 onto kantar patch branch

src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt, src/main/kotlin/org/wfanet/panelmatch/client/tools/DecryptPrivateMembershipQueryResults.kt
Adds a tool for a standalone panel exchange private query decryption job.
=> Standalone px decrypt

src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt
This cherry picks 77fd9b3a4d8ad660a14b5fdc88c1d5266958a8cc
=> Cherry pick private key blob key

experimental/reporting-ui/src/main/react/reporting-ui/component/chart/chart.tsx, experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.css, experimental/reporting-ui/src/main/react/reporting-ui/component/chart/d3_wrapper.js, experimental/reporting-ui/src/main/react/reporting-ui/component/chart/total_reach/total_reach.tsx, experimental/reporting-ui/src/main/react/reporting-ui/component/chart/unique_reach_by_plat/unique_reach_by_plat.tsx
Notes:
* Chart features:
* Adding a new chart type (multi-bar not percentage).
* Updating existing draw bar function (was removed from use so last PR didn't break anything).
* Adding a legend.
* Updating chart titles.
* Chart bugs:
* Setting a max height on the charts so they can always be viewable in a screen.
* Adding a chart redraw method and a window resize event. If the window size changed, the charts wouldn't resize. D3 has a responsive SVG attribute but that doesn't apply to fonts.
* Adding a style so the charts can be scrollable on small screens.
* Updating tick count so it makes more sense with fewer x-axes values.
=> Updating Charts and fixing some Chart Bugs

src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/bigquery_edp_simulator_gke.cue, src/main/k8s/dev/edp_simulator_gke.cue
This addresses an issue that was missed in #1324.
=> Fix simulator service account not being created for GKE.

src/main/k8s/dev/base_eks.cue, src/main/k8s/dev/base_gke.cue, src/main/k8s/dev/duchy_eks.cue, src/main/k8s/dev/duchy_gke.cue
This supports larger sketch sizes.
=> Increase heap size for dev requisition fulfillment server.

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGenerationTest.kt
This is a performance optimization.
=> Only generate synthetic events within specified time range.

src/main/k8s/dev/duchy_eks.cue, src/main/k8s/dev/duchy_gke.cue, src/main/k8s/duchy.cue
This is to support the current sketch size configuration.
=> Increase work lock duration for dev LLv2 mills.

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
=> Populate Requisition.encrypted_requisition_spec_ciphertext field.

MODULE.bazel, src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt, src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt, src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
=> Populate MeasurementSpec.serialized_measurement_public_key field.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamStateTransitionMeasurementLogEntries.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsServiceTest.kt
=> Log state transition to SUCCEEDED for MPC Measurements.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/SpannerQuery.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/SpannerReader.kt, src/main/resources/kingdom/spanner/changelog.yaml, src/main/resources/kingdom/spanner/reorder-measurements-by-continuation-token.sql
* Reorder index columns to actually be useful for query.
* Apply clauses to Measurements table before other joins.
=> Improve performance of StreamActiveComputations query.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt
The request ID index isn't actually being used right now. Instead, a table scan is being done. This refactors the query to actually use the index.
=> Use index in existing Measurements check when creating Measurements

src/main/proto/wfa/panelmatch/client/internal/BUILD.bazel, src/main/proto/wfa/panelmatch/client/internal/exchange_step_attempt.proto, src/main/proto/wfa/panelmatch/client/internal/exchange_workflow.proto
Messages: ExchangeWorkflow, ExchangeStepAttempt
=> Create panel match internal versions of protobuf messages

src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel, src/main/proto/wfa/measurement/system/v1alpha/computation_participants_service.proto
Fixed an error introduced in #1657
=> Fix api-linter error in system GetComputationParticipant.

src/main/kotlin/org/wfanet/measurement/api/v2alpha/PackedMessages.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
=> fix: ensure CreateEventGroup succeeds with legacy MC public key

src/main/docker/images.bzl, src/main/k8s/dev/duchy_eks.cue, src/main/k8s/dev/duchy_gke.cue, src/main/k8s/duchy.cue, src/main/kotlin/org/wfanet/measurement/duchy/deploy/aws/job/mill/shareshuffle/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/aws/job/mill/shareshuffle/S3HonestMajorityShareShuffleMillJob.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/shareshuffle/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/shareshuffle/ForwardedStorageHonestMajorityShareShuffleMillJob.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/shareshuffle/HonestMajorityShareShuffleMillFlags.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/shareshuffle/HonestMajorityShareShuffleMillJob.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/job/mill/shareshuffle/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/job/mill/shareshuffle/GcsHonestMajorityShareShuffleMillJob.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/MillFlags.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/MillType.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt, src/main/kotlin/org/wfanet/measurement/duchy/mill/shareshuffle/HonestMajorityShareShuffleMill.kt, src/test/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobSchedulerTest.kt
This converts the HMSS Mill daemon to a Job which is scheduled by the MillJobScheduler daemon.
=> feat!: enable horizontal autoscaling of HMSS Mill

MODULE.bazel
This should also address #1736
=> build: Update common-jvm dep for Java base image.

src/main/terraform/aws/modules/eks-cluster/main.tf
This exports container logs to CloudWatch.
=> feat: Enable CloudWatch Observability EKS add-on

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
feat: Increase chance of getting Event Groups from Reporting Server ListEventGroups
=> feat: Increase chance of getting Event Groups from Reporting Server ListEventGroups

docs/eks/duchy-deployment.md, docs/gke/duchy-deployment.md, src/main/k8s/duchy.cue
=> fix!: Add missing NetworkPolicy for Mill job scheduler

build/variables.bzl, src/main/k8s/panelmatch/dev/BUILD.bazel, src/main/k8s/panelmatch/dev/config.cue, src/main/k8s/panelmatch/dev/config_aws.cue, src/main/k8s/panelmatch/dev/config_gke.cue, src/main/k8s/panelmatch/dev/daemon_config.cue, src/main/k8s/panelmatch/dev/kingdomless_daemon_aws.cue, src/main/k8s/panelmatch/dev/kingdomless_daemon_gke.cue
This introduces CUE files with important panel exchange flags configurable via tags using `--define`.
=> feat: Expose panel exchange flags via CUE tags

src/main/terraform/gcloud/modules/kingdom/main.tf
fix: Switch to project id variable from hard coded project id
=> fix: Switch to project id variable from hard coded project id

third_party/rbe_configs/cc/BUILD, third_party/rbe_configs/cc/cc_toolchain_config.bzl, third_party/rbe_configs/cc/cc_wrapper.sh
This was performed by running tools/gen-rbe-configs.
=> build: Update RBE configs for Bazel 7.3.1

src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
test: Add explicit unit test and integration test for end of Report time interval
=> test: Add explicit unit test and integration test for end of Report time interval

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
=>  fix: check updated and created fields before assignment

src/main/k8s/dev/kingdom_gke.cue, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExportJob.kt, src/main/proto/wfa/measurement/internal/kingdom/bigquerytables/operational_metrics_dataset.proto, src/main/terraform/gcloud/modules/kingdom/main.tf, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExportTest.kt
feat: Add new Bigquery Table for Computation Participant Stages
=> feat: Add new Bigquery Table for Computation Participant Stages

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto
feat: Add new filter for checking externalComputationId, and checking externalComputationId if view is COMPUTATION or COMPUTATION_STATS
=> feat: Add new filter for checking externalComputationId, and checking externalComputationId if view is COMPUTATION or COMPUTATION_STATS

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeyAuthenticationServerInterceptor.kt
https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/839
=> fix:Handle ApiKey authentication error when it is invalid.

src/main/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProvider.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
=> fix: Include known types when building EventGroup filter registry

src/main/kotlin/org/wfanet/measurement/access/service/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/access/service/Errors.kt, src/main/kotlin/org/wfanet/measurement/access/service/IdVariable.kt, src/main/kotlin/org/wfanet/measurement/access/service/PermissionKey.kt, src/main/kotlin/org/wfanet/measurement/access/service/PrincipalKey.kt, src/main/kotlin/org/wfanet/measurement/access/service/RoleKey.kt, src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsService.kt, src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/ResourceConversion.kt, src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt, src/main/proto/wfa/measurement/access/README.md, src/main/proto/wfa/measurement/access/v1alpha/principals_service.proto, src/main/proto/wfa/measurement/access/v1alpha/roles_service.proto, src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/PrincipalsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt
These two methods are being implemented first to demonstrate the general pattern and make it easier for another engineer to implement the rest.
=> feat: Implement Access GetPrincipal and UpdateRole 

build/defs.bzl, src/main/proto/wfa/measurement/reporting/v2alpha/BUILD.bazel
This avoids duplication of boilerplate code.
Replaces #2025
=> refactor: Use list comprehensions for Reporting proto BUILD

src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py, src/test/python/wfa/measurement/reporting/postprocessing/report/test_report.py
=> fix: Removes incorrect consistency check in the report post-processing.

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt
This avoids a full table scan when querying Requisitions by MeasurementConsumer ID.
=> perf: Order Requisitions joins based on WHERE clause

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BaseSpannerReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt
This is intended to assist with debugging. See https://cloud.google.com/spanner/docs/introspection/troubleshooting-with-tags
=> feat: Tag Kingdom Spanner transactions with reader/writer class

src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPoliciesService.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPrincipalsService.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerRolesService.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/db/Permissions.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/db/Policies.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/db/Principals.kt, src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/db/Roles.kt
See #2088, which does something similar for the Kingdom.
=> feat: Tag Access Spanner transactions with action

src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/testing/Schemata.kt, src/main/resources/securecomputation/spanner/BUILD.bazel, src/main/resources/securecomputation/spanner/changelog.yaml, src/main/resources/securecomputation/spanner/create-securecomputation-schema.sql, src/main/resources/securecomputation/spanner/create_securecomputation_schema.sql, src/test/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/SecurecomputationSchemaTest.kt
=> feat: add schema creation for controlplane persistency

src/main/terraform/gcloud/cmms/.terraform.lock.hcl, src/main/terraform/gcloud/cmms/versions.tf, src/main/terraform/gcloud/examples/duchy/versions.tf, src/main/terraform/gcloud/examples/kingdom/versions.tf, src/main/terraform/gcloud/examples/reporting/versions.tf, src/main/terraform/gcloud/examples/simulators/versions.tf, src/main/terraform/gcloud/modules/node-pool/versions.tf
This includes a fix for hashicorp/terraform-provider-google#19792
=> fix: Update Google Terraform provider to 6.23.0

src/test/kotlin/org/wfanet/panelmatch/integration/BUILD.bazel
=> ci: Mark panel match integration tests as flaky

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelLineReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/all_protos.bzl, src/main/proto/wfa/measurement/internal/kingdom/data_provider.proto, src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, src/main/proto/wfa/measurement/internal/kingdom/model_line_key.proto, src/main/resources/kingdom/spanner/changelog.yaml, src/main/resources/kingdom/spanner/create-data-provider-availability.sql, src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt
This implements world-federation-of-advertisers/cross-media-measurement-api#226
=> feat: Support DataProvider.data_availability_intervals

MODULE.bazel, MODULE.bazel.lock, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataAvailabilityIntervals.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/data_providers_service.proto
This implements world-federation-of-advertisers/cross-media-measurement-api#229
=> feat: Implement DataProviders/ReplaceDataAvailabilityIntervals

src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsService.kt, src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel, src/main/proto/wfa/measurement/internal/kingdom/requisition_details.proto, src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, src/main/proto/wfa/measurement/system/v1alpha/requisition.proto, src/main/proto/wfa/measurement/system/v1alpha/requisitions_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
Implements world-federation-of-advertisers/cross-media-measurement-api#228
=> feat: Support Requisition.fulfillment_context

src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/BUILD.bazel
fix https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/2200
=> feat: Add internal_api_server_image to Secure Computation

src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/v1alpha/WorkItemsService.kt, src/test/kotlin/org/wfanet/measurement/securecomputation/controlplane/v1alpha/WorkItemServiceTest.kt
Fixes a defect where the public api was properly creating the internal request to the internal api
=> fix: public control plane api create proper internal api request

src/main/terraform/gcloud/cmms/edp_aggregator.tf, src/main/terraform/gcloud/modules/edp-aggregator/main.tf, src/main/terraform/gcloud/modules/edp-aggregator/variables.tf, src/main/terraform/gcloud/modules/mig/main.tf, src/main/terraform/gcloud/modules/mig/variables.tf
This references an artifact registry that we do not use.
=> fix: Remove artifact registry from mig terraform file

.github/workflows/update-cmms.yml
There are issues with this on the head environment.
=> fix: Remove deploy cloud function from update cmms workflow

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt, src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt
=> fix: Treat rhs operand of composite ReportingSet as optional

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
This implements the API changes introduced in #2194.
=> feat: Support structured filter and order by in Reporting ListEventGroups

src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt
=> fix: Read Measurements in batches for CompletedMeasurementsDeletion

.github/workflows/terraform-cmms.yml
This fixes deployment for Halo-managed environments, which no longer include AWS.
=> fix: Drop AWS from Terraform workflow

src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/common/SqlBasedQuery.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelLineReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/PopulationReader.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDuchyMeasurementLogEntry.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelOutage.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelShard.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt
This expands upon #2088 to cover missing queries.
=> feat: Ensure all Kingdom Spanner queries are tagged

MODULE.bazel, MODULE.bazel.lock
=> build: Update common-jvm dep for Spanner deadlock

MODULE.bazel, MODULE.bazel.lock
Issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/2137
=> build: Update common-jvm to fix freetype vulnerability

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt
This also avoids unnecessary joins/columns when reading the EventGroup for update.
Issue: #2433
=> perf: Write NULL rather than default to EventGroupDetails column when not set

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
=> fix: Persist Requisition FulfillmentContext

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt
=> fix: Convert data availability start time to google.cloud.Timestamp

src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/FilterConfiguration.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/FilterProcessor.kt, src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/FilterProcessorTest.kt
This PR introduces the FilterProcessor:
- A class to filter LabeledEvent objects in the event pipeline.
- Processing events as EventBatch objects
- Pre-compiles a porgam to perform CEL filtering
=> Filter Processing

.github/actions/configure-metrics/action.yml, src/main/k8s/open_telemetry.cue
This was missed in #2702.
Issue: #2701
=> fix: Update OpenTelemetry Contrib to be compatible with Operator

src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/AbstractEdpSimulator.kt, src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt, src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
=> fix(edp-simulator): Refuse requisition when event filter is invalid for HMSS

.github/workflows/check-donotsubmit.yml
=> ci: Add check to block merging PRs with DO_NOT_SUBMIT comments

src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BasicReportTransformations.kt, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BasicReportTransformationsTest.kt
Create MetricCalculationSpec Groupings from DimensionSpec Grouping.
Issue: #2608
=> feat: Create MetricCalculationSpec Groupings for BasicReport

MODULE.bazel, MODULE.bazel.lock, src/main/kotlin/org/wfanet/measurement/common/grpc/ApiChangeMetricsInterceptor.kt, src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/common/grpc/Interceptors.kt, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/RequisitionFulfillmentServer.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt, src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel, src/main/proto/wfa/measurement/type/BUILD.bazel
=> feat: Collect API change metrics for CMMS public API

src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/EventBatch.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/FilterSpec.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/LabeledEvent.kt
This commit introduces foundational data structures and types that support the event processing pipeline:
- LabeledEvent: Core data structure for events with associated metadata
- FilterSpec: Specification for filter processing
- EventBatch: Container for batched event processing
=> feat: core data models for event processing

src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/BUILD.bazel, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/EventProcessingOrchestrator.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/EventReader.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/PipelineConfiguration.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/StorageEventReader.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/StorageEventSource.kt, src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/StorageImpressionMetadataService.kt, src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/BUILD.bazel, src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/EventProcessingIntegrationTest.kt, src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/EventReaderTest.kt
=> feat: event processing orchestrator

.github/workflows/build-test.yml
=> ci: Add local K8s configuration targets to build-test workflow.

build/variables.bzl, docs/gke/population-requisition-fulfiller-deployment.md, src/main/k8s/dev/BUILD.bazel, src/main/k8s/dev/README.md, src/main/k8s/dev/pdp_config_kustomization.yaml, src/main/k8s/dev/pdp_cs_kustomization.yaml, src/main/k8s/dev/pdp_tls_kustomization.yaml, src/main/k8s/dev/population_requisition_fulfiller_gke.cue, src/main/k8s/population_requisition_fulfiller.cue, src/main/k8s/testing/secretfiles/BUILD.bazel
=> feat: Add cloud K8s configuration for Population Requisition Fulfiller

.github/workflows/configure-population-fulfiller.yml, .github/workflows/update-cmms.yml
=> feat: Update population requisition fulfiller in Halo-managed environments

src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelRolloutsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteModelRollout.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ScheduleModelRolloutFreeze.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelLinesService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt, src/main/proto/wfa/measurement/internal/kingdom/error_code.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsServiceTest.kt
This implements world-federation-of-advertisers/cross-media-measurement-api#251
Issue: #2920
=> feat: Allow retroactive creation of ModelLines and ModelRollouts

src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelLineKey.kt, src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelReleaseKey.kt, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamModelRollouts.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsService.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelRolloutsServiceTest.kt, src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt, src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, src/main/proto/wfa/measurement/internal/kingdom/model_rollouts_service.proto, src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelRolloutsServiceTest.kt
This implements world-federation-of-advertisers/cross-media-measurement-api#253
Closes #2933
Issue: #2933
=> feat: Support listing ModelRollouts by ModelRelease
