- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesServiceTest.kt
This just adds the basic Kotlin classes and some tests that expect the
services to throw NotImplementedErrors. Future commits will fill in the
logic.
See issue world-federation-of-advertisers/cross-media-measurement#3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5)
> Implement skeletons of Panel Match public APIs.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/kingdom.sdl
This is to support the centralized APIs for panelist exchange, e.g.
/RecurringExchanges, /Exchanges, and others added in
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/commit/0c1d7b0a926b3e7f7ad3e6f51d99fefdaf18bdd5
See issue world-federation-of-advertisers/cross-media-measurement#3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/4)
> Add Panel Match tables to Kingdom.

- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt.proto
- src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt_details.proto
- src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto
- src/main/proto/wfa/measurement/internal/kingdom/exchanges_service.proto
- src/main/proto/wfa/measurement/internal/kingdom/recurring_exchanges_service.proto
For now, this adds a minimal set of methods required to implement most
of the functionality of the public facing APIs.
As more functionality is required, these will need to be expanded.
Building them incrementally has the advantage of not needing to
implement methods that are later determined to be unnecessary.
See world-federation-of-advertisers/cross-media-measurement#3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/10)
> Add Kingdom-internal Panel Match data-layer gRPC service definitions.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/DataServices.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ReportConfigSchedulesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ReportConfigsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ReportLogEntriesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ReportsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/CorrectnessImpl.kt
- src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/server/GcpKingdomDataServerTest.kt
This replaces the usages with the super-interfaces introduced in
commit 556ba60.
The next step will be to split apart the implementation of
KingdomRelationalDatabase, SpannerKingdomRelationalDatabase, into
implementations of the super-interfaces. After that,
KingdomRelationalDatabase can finally be removed.
> Remove most usages of KingdomRelationalDatabase.

- WORKSPACE
There is a build failure/
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/5efb41e3bf38a44ce0efecb45b2f3782/external/io_bazel_rules_docker/container/go/cmd/extract_config/BUILD:19:11: @io_bazel_rules_docker//container/go/cmd/extract_config:go_default_library depends on @com_github_google_go_containerregistry//pkg/v1/tarball:go_default_library in repository @com_github_google_go_containerregistry which failed to fetch. no such package '@com_github_google_go_containerregistry//pkg/v1/tarball': java.io.IOException: Error downloading [https://api.github.com/repos/google/go-containerregistry/tarball/8a2841911ffee4f6892ca0083e89752fb46c48dd] to /home/runner/.cache/bazel/_bazel_runner/5efb41e3bf38a44ce0efecb45b2f3782/external/com_github_google_go_containerregistry/temp16100567993540712573/8a284 …
```
> Fixed com_github_google_go_containerregistry

- WORKSPACE
> Update to newer version of rules_docker to fix dependency breakage.

- build/cloud_spanner_emulator/defs.bzl
- build/cue/defs.bzl
- build/cue/repo.bzl
- build/macros.bzl
- build/platforms/BUILD.bazel
- build/platforms/constraints.bzl
This allows other repositories to take a dependency on
cross-media-measurement without needing to clone parts of /build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/46)
> Qualify bazel references with workspace name in /build.

- WORKSPACE
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt
- src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempts_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt
This also moves the internal ExchangeStepAttempts service to be in
parity with the public API version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/51)
> Update cross-media-measurement-api version.

- src/test/cc/testutil/BUILD.bazel
- src/test/cc/testutil/matchers.h
Source: https://github.com/world-federation-of-advertisers/any-sketch/blob/main/src/test/cc/testutil/matchers.h.
VID code requires util matchers in both cross-media-measurement and
any-sketch repos, but the file names conflict. For short term solution, we
will have all the required util matchers for VID in cross-media-measurement repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/67)
> Copy util matchers from Any Sketch repo.

- src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto
- src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto
We expect a small set of well-known Duchies, so we can use human-readable strings for their external IDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/62)
> Change data type of external_duchy_id to string.

- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/certificate.proto
This includes some fields denormalized from the X.509 certificate so they can be queried.
For issue #52.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)
> Define Certificate message type for Kingdom internal services.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/81)
> Add tables for Certificates to Kingdom Spanner schema.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl
- src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto
- src/main/proto/wfa/measurement/system/v1alpha/BUILD.bazel
- src/main/proto/wfa/measurement/system/v1alpha/computation_log_entries_service.proto
- src/main/proto/wfa/measurement/system/v1alpha/computation_log_entry.proto
- src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto
- src/main/proto/wfa/measurement/system/v1alpha/computation_participants_service.proto
- src/main/proto/wfa/measurement/system/v1alpha/stage_attempt.proto
This can be used by a Duchy to indicate a permanent error, transitioning the parent Computation to the FAILED state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/91)
> Replace the RefuseComputationParticipant method with FailComputationParticipant.

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt
- src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
The mill will use this order of the computationParticipants list as
the source of truth of the mpc ring structure.
Also renamed GlobalComputationService to SystemComputationService in the herald.
However, the kingdom's computation id is still called GlobalId or
GlobalComputationId, since word "Global" is already used in the database
column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/97)
> Order the computationParticipants by their order in the MPC ring.

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniLiquidLegionsV2Encryption.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/LiquidLegionsV2Encryption.kt
- src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationProtocolStageDetails.kt
- src/main/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2Protocol.kt
- src/main/kotlin/org/wfanet/measurement/duchy/db/computation/testing/FakeComputationsDatabase.kt
- src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_sketch_aggregation_v2.proto
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniLiquidLegionsV2EncryptionTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClientsTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/db/computation/LiquidLegionsSketchAggregationV2ProtocolEnumStagesDetailsTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/service/internal/computation/ComputationsServiceTest.kt
Behavior change:
previously, the mill would fetch all local requisitions from the
metricValueService and store the combined sketch locally for the future
processing.
Now, the mill just verify requistions status based on the database information,
no blob read/write is done.
so the output blob number of the INITIALIZATION_PHASE changes from 1 to
0. And there is no input blob for the WAIT_TO_START and
WAIT_SETUP_PHASE_INPUT stages any more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)
> Update the confirmationPhase processor in the llv2 mill.

- .gitignore
- AUTHORS
- src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt
- src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
- src/main/kotlin/org/wfanet/measurement/common/identity/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomApiServer.kt
- src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt
Added support for TLS for the gRPC servers by providing command line flags for configuring cert & key files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/77)
> Add TLS support for gRPC servers

- docs/building.md
As per our discussion yesterday, adding a few instructions to the doc so they're not getting lost before the next person onboards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/101)
> Add IntelliJ instructions

- src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt
- src/main/kotlin/org/wfanet/measurement/duchy/db/computation/ComputationDataClients.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillDaemon.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillFlags.kt
- src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_sketch_aggregation_v2.proto
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt
Two key changes:
1. In the setup phase, the data is now read from the
requisitionBlobs instead of from the stage input blob.
2. The parameters of all crypto library calls now come from
the computationDetails instead of from the mill's configuration.
In other words, no shared parameters for all computations anymore.
Also updated the test to use kotlin style apply{} for all proto
messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/105)
> Update llv2 mill implementation for all execution phases.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto
- src/main/proto/wfa/measurement/internal/kingdom/computation_participants_service.proto
- src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto
- src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entry.proto
- src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/118)
> Define internal Kingdom ComputationParticipants and MeasurementLogEntries services.

- WORKSPACE
This overrides the default version specified by grpc-kotlin. It prevents KotlinCompile warnings regarding having multiple runtime JARs with different versions (e.g. kotlin-stdlib, kotlin-reflect).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/158)
> Update KotlinPoet to a version that uses Kotlin 1.4.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/DataProvidersServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/151)
> Implement v2alpha public API DataProviders service.

- WORKSPACE
- src/test/cc/testutil/BUILD.bazel
- src/test/cc/testutil/matchers.h
- src/test/cc/testutil/status_macros.h
- src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/BUILD.bazel
- src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc
Reverts world-federation-of-advertisers/cross-media-measurement#162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/163)
> Revert "Migrate testutil dependency to common_cpp"

- src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsService.kt
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/measurement.proto
- src/main/proto/wfa/measurement/internal/kingdom/requisition.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/RequisitionsServiceTest.kt
These were needed to populate the matching public API messages. The Requistion fields that are denormalized from the parent Measurement are now not populated for the NORMALIZED Requisition view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)
> Add missing fields to internal Measurement/Requisition.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto
- src/main/proto/wfa/measurement/internal/kingdom/measurement.proto
- src/main/proto/wfa/measurement/internal/kingdom/requisition.proto
- src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
* The `details_json` fields were added unintentionally to the protobuf API. JSON serialization of Details columns is purely for DB debugging.
* `ComputationParticipant` doesn't need a `create_time` field as its created as part of the parent `Measurement`, and the field isn't used for anything.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)
> Remove unnecessary fields from Kingdom internal API.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/252)
> Fix inaccurate test method names in ComputationParticipantsServiceTest.

- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/277)
> Increase the tolerance in the noisy result equality check.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/276)
> Check if there are duplicated dataProvider entries in the measurement.

- src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt
It is causing an issue when multiple EDPs are fulfilling their
requisitions at the same time.
There is no need to require the caller of writeRequisitionBlobPath() to own
the most recent token. writeRequisitionBlobPath() is called by the
requsitionFulfillmentService, which doesn't claim the lock of a computation
before updating it.
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/289)
> Don't use runIfTokenFromlastUpdate for writeRequisitionBlobPath().

- src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt
- src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt
This will be used in the in-memory integrationTest, which uses InProcessChannel and has no TLS conext
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)
> Define a MetaDataDuchyIdInterceptor.

- .bazelrc
- build/platforms/BUILD.bazel
- build/platforms/constraints.bzl
- build/repositories.bzl
common-jvm v0.15.0 specifies new Distroless Java images based on Debian 11 (Bullseye), which have glibc 3.31.
This also adds convenience platform configurations for local .bazelrc. For example, if your platform is Debian Bullseye then you can add `build --config=debian-bullseye` to your local .bazelrc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/304)
> Mark Distroless Java as being compatible with glibc 3.31.

- tools/bazel-container
This fixes an issue introduced in #307 where the Bazelisk cache dir inside the container would be incorrect unless Docker were being run in rootless mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/309)
> Specify BAZELISK_HOME in bazel-container.

- src/main/kotlin/org/wfanet/measurement/duchy/storage/ComputationStore.kt
- src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt
The `/` in the prefix results in an additional folder with empty name.
The `SketchStore` is missing a `/` in front of the blobKey.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)
> Fix the blobpath.

- tools/bazel-container
* Check Bash version.
* MacOS comes preinstalled with a very old version of Bash (major version 3).
* Determine correct user output root directory without relying on Bazel being installed on the host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/357)
> Improve MacOS compatibility of tools/bazel-container script.

- tools/bazel-container
This is a behavioral change where the build output of the script is isolated from the host filesystem. The workspace directory is mounted as readonly and any convenience symlinks are left untouched. The script still bind mounts the Bazelisk cache and repository cache from the host filesystem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/362)
> Use a Docker volume `bazel-output` for bazel-container output.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
Also fixed a bug in the frontendSimulator that all EDPs use the same
nouce.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/380)
> Validate measurementSpec.nounceHashes when creating new measurement.

- docs/building.md
- tools/bazel-container
This changes the remote Bazel output base to be $PWD/bazel-container-output, allowing linux-x64 hosts to run binaries built inside the container by creating a corresponding symlink pointing to the volume mount point.
This also mounts the gcloud SDK config in Bazel container so that the container an access the host machine's credentials for GKE deployment.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/378)
https://rally1.rallydev.com/#/?detail=/task/615894450943&fdp=true
> Better support containerized builds when developing on Linux environments.

- WORKSPACE
- imports/java/com/opentable/db/postgres/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/testing/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/testing/Schemata.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/testing/exchange.sql
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel
This is more of a request for comments and to:
* Make sure github's CI will be able to run embedded postgres in testing
* Help decide if we want to go the route of using embedded postgres for unit testing
* Find a simple way for testing schema migration from Spanner to Postgres
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)
> Add pg-embedded to test a minimal postgres schema validation

- build/cue/defs.bzl
- src/main/k8s/BUILD.bazel
- src/main/k8s/dev/BUILD.bazel
- src/main/k8s/macros.bzl
This allows sharing of CUE libraries without depending on source files from other Bazel packages, which is against best practices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/415)
> Add cue_library rule.

- build/variables.bzl
- src/main/k8s/base.cue
- src/main/k8s/dev/BUILD.bazel
- src/main/k8s/dev/frontend_simulator_gke.cue
- src/main/k8s/dev/kingdom_gke.cue
- src/main/k8s/dev/resource_setup_gke.cue
- src/main/k8s/duchy.cue
- src/main/k8s/frontend_simulator.cue
- src/main/k8s/kingdom.cue
- src/main/k8s/local/BUILD.bazel
- src/main/k8s/local/frontend_simulator.cue
- src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt
- src/main/kotlin/org/wfanet/measurement/tools/BUILD.bazel
The test was broken since we have made plenty changes to the system.
For example, principal authority and mark variables related changes.
The PR also
1. uploaded a synthetic-labelled-events.csv for completing correctnessTest
on GKE
2. switched the order of EDP and MC creation in the resourceSetupJob to
make sure we call the kingdom public API first. Otherwise, the job may
call the internal kingdom API successfully and fail later when calling
the public API. If this happens, the retry would fail constantly since
the EDPs are already created.
3. Deleted the labels in the NetworkPolicy, since NetworkPolicy doesn't
supoort labels.
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F619653855975
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Fix the GKE correctnessTest deployment.

- build/cue/defs.bzl
- src/main/k8s/dev/BUILD.bazel
- src/main/k8s/local/BUILD.bazel
- src/main/k8s/macros.bzl
From https://docs.bazel.build/versions/4.2.2/skylark/rules.html#outputs:
> Prefer using non-predeclared outputs and explicitly adding outputs to DefaultInfo.files. Use the rule target’s label as input for rules which consume the output instead of a predeclared output’s label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/428)
> Use default output rather than predeclared output for cue_export

- docs/building.md
- docs/gke/correctness-test.md
- docs/gke/duchy-deployment.md
- docs/gke/kingdom-deployment.md
- docs/gke/machine-setup.md
Use of the scripts for containerized builds are very dependent on the build environment. This adds references to the building doc instead, and indicates that the reader may need to adjust their commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/439)
https://rally1.rallydev.com/#/?detail=/task/626955042001&fdp=true
> Use bazel rather than containerized scripts in deployment commands.

- WORKSPACE
- imports/java/org/projectnessie/cel/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt
- src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt
- src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt
Adds a validator of Event Filtering expressions that will use the Common Expression Language.
It validates that the expression fits Halo's limitations in terms of structure and operators that are allowed.
(type validation will be in the next component, an Evaluator, that will interpret the fields referenced in the expression).
Note: this is on top of @uakyol's PR, so we can have feedback on how both workflows work together
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)
> Event filter CEL expression validation

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversionsTest.kt
In general, exchange steps should not have the same blob key in both their input map and output map, as this causes the step to be its own prerequisite and thus can never enter a READY state. The only exception is CopyFromPreviousExchangeStep which must have the same input and output blob key in order to work correctly. For this type of step, explicitly remove its index from the prerequisite indices so that it can be properly scheduled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489)
> Ensure an exchange step is not its own prerequisite.

- src/main/kotlin/org/wfanet/measurement/loadtest/config/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/config/EventFilters.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorRunner.kt
Fixes the local correctness test by adding EventFilters to Frontend simulator runner and the EDPSimulator runner
Tested with instructions from https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/local/README.md#local-kubernetes-deployment and verified the correctness 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/508)
> Fix local correctness test by passing in Event Templates to Simulators

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilterException.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel
- src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidatorTest.kt
Creates an event filtering library that will match a CEL expression to an event Message
* Event Message's are defined as proto's that have all valid event templates as optional fields
* The name of the template field, within the event message, is used for reference by variables in the CEL expression
* The EventFilter only needs a default Event Message to initialize the CEL environment, and compile the expression
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)
> Add event filtering

- src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/Schemata.kt
- src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql
- src/test/kotlin/org/wfanet/measurement/integration/postgres/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt
* Creates a schema for the Privacy Bucket Ledger backing store using postgresql notation
* Run the schema and a basic write/read as a basic test, under a postgres docker test harness already implemented in the project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)
> Add postgres schema and test for privacy budget ledger

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedComposition.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AdvancedCompositionTest.kt
This increases the performance of this lookup significantly.  
totalPrivacyBudgetUsageUnderAdvancedComposition works in O(repetition_count^2) and it runs this unnecessarily for all PrivacyBucketGroups that have the same charge.
It will now run O(1) for all PrivacyBucketGroups after the first calculation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/551)
> Memoization for advanced composition theorem

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelProviderCertificateKey.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReleaseCertificateHold.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/certificate.proto
- src/main/proto/wfa/measurement/internal/kingdom/certificates_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt
Revert [PR #522](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/522).
CertificateService will keep taking care of certificate for ModelProvider. But ModelProvider itself won't have concepts of certificate or public_key.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/556)
> Revert back Certificate for ModelProvider

- docs/building.md
- tools/bazel-container
This avoids volume permissions issues when doing hybrid development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/565)
> Use bind mount on Linux hosts for containerized builds.

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/panelmatchresourcesetup/PanelMatchResourceSetupRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt
- src/main/kotlin/org/wfanet/measurement/system/v1alpha/IdVariable.kt
This fixes appropriate warnings/errors for upgrading to Kotlin language 1.5 and kotlinx-coroutines 1.6. In particular, it drops the usage of GlobalScope which is now marked as a delicate API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/582)
> Update common-jvm to 0.36.0.

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt
Previously, it was done one by one which would have induced thousands of roundtrips.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/617)
> Insert Balance Entries in batch

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
Don't generate protocolConfig for direct reach and frequency measurement(count of dataProvider is equal to 1) so MPC computation will not be triggered
Add Laplace noise to reach and frequency result in direct measurement in EDP simulator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/619)
> Don't generate internal protocolConfig for direct reach and frequency measurement

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt
The differential privacy protocols currently in use for Liquid Legions v2 require that delta > 0.  If a 0 value of delta was supplied, the C++ code for sketch creation and noising would generate an exception, causing the duchy to crash.  This patch causes the herald to check for a non-zero value of delta before further processing is allowed.  If a zero value is found, then the Herald generates an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/607)
> Reject zero values of delta

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepAttemptsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepAttemptsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt
- src/main/proto/wfa/measurement/internal/kingdom/error_code.proto
This fixes StatusRuntimeExceptions being thrown from Spanner transaction executors, which breaks exception handling in the Spanner API client.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/673)
> Update common-jvm to 0.45.1.

- docs/gke/kingdom-deployment.md
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/kingdom_gke.cue
- src/main/k8s/local/duchies.cue
- src/main/k8s/local/kingdom.cue
- src/main/k8s/testing/secretfiles/resource_requirements.yaml
It appears that these limits were too low (e.g. resulting in Spanner transactions taking tens of seconds). This allows containers to utilize unclaimed CPU. The amount of CPU available to utilize will depend on the node pool configuration.
We may wish to specify CPU requests to ensure that containers don't get starved for resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/687)
> Drop CPU limits from K8s resource requirements.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt
Spanner monitoring showed that these queries were consuming significant CPU, scanning orders of magnitude more rows than necessary and having >1s average latency.
Sample avg latency reduction:
ComputationParticipant by Computation ID 5491ms -> 544ms
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/688)
> Fix inefficient Spanner query joins.

- .gitignore
- src/main/k8s/local/README.md
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMap.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStore.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
- src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto
- src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/EncryptionKeyPairMapTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStoreTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
Enable multi tenancy for the reporting server by making `EncryptionKeyPairStore` handles private key pairs by principal.
* Consumers of the key pair store now pass the principal along with the public key in order to retrieve the private key
* Configuration using textproto for `EncryptionKeyPairConfig` message is updated to define key pairs by principal 
* Doesn't change the current way of obtaining the key pairs by by loading from each key file path
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)
> Separate key pairs in EncryptionKeyPairStore by principal

- src/test/kotlin/org/wfanet/measurement/integration/gcloud/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/integration/gcloud/GCloudInProcessLifeOfAMeasurementIntegrationTest.kt
This avoids false failures in low-CPU environments such as GitHub Actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/720)
> Increase timeout for GCloudInProcessLifeOfAMeasurementIntegrationTest.

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/SystemApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt
StatusException should be caught at the lowest level, i.e. the call site of the RPC. This is because how a given error should be handled depends on which method was being called. If it needs to be handled at a higher level, it should be wrapped in another exception type to make that explicit to calling code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/714)
> Catch more RPC exceptions.

- src/main/k8s/resource_setup.cue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/729)
> Fix ResourceSetup to use Kingdom certs rather than MC certs.

- docs/gke/duchy-deployment.md
- docs/gke/kingdom-deployment.md
- src/main/k8s/base.cue
- src/main/k8s/dev/base_gke.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/local/edp_simulators.cue
This configures those Deployments to tolerate node pools with a `NoSchedule` taint for `cloud.google.com/gke-spot`.
See http://cloud/kubernetes-engine/docs/how-to/spot-vms#use_taints_and_tolerations_for
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)
> Allow dev Mill and Herald to run on GKE Spot VMs.

- docs/gke/duchy-deployment.md
- docs/gke/kingdom-deployment.md
- docs/gke/reporting-server-deployment.md
- src/main/k8s/local/README.md
* Add missing duchy_cert_config.textproto entry in Duchy deployment doc.
* Fix misleading EncryptionKeyPairConfig sample in local reporting server deployment doc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/735)
> Fix deployment docs.

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/integration/deploy/gcloud/InProcessKingdom.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/proto/wfa/measurement/internal/kingdom/measurement.proto
- src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
- Kingdom supports repeated protocols in public protocol_config for requisition to specify if a measurement is direct reach and frequency measurement(single data provider). This way EDP can decide to do direct or MPC based reach and frequency computation for direct measurement. The internal protocol_config will remain unchanged
- Add Kingdom flag --allow-mpc-protocols-for-single-data-provider to control adding MPC protocol for single-edp reach and frequency measurement
- Update relevant unit tests and integrations tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/728)
> Kingdom supports repeated protocols in public protocol_config

- docs/gke/duchy-deployment.md
- docs/gke/kingdom-deployment.md
- src/main/k8s/base.cue
- src/main/k8s/dev/base_gke.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/kingdom_gke.cue
- src/main/k8s/dev/reporting_gke.cue
- src/main/k8s/dev/resource_requirements.yaml
- src/main/k8s/local/config.cue
Percentage sizes do not allow for scaling heap memory independently of non-heap memory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/745)
> Use fixed sizes for JVM memory in dev environment.

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
The DuchyEntry.Value.duchy_certificate field was incorrectly being populated with the Certificate ID rather than the Certificate resource name.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/775)
> Fix incorrect Duchy certificate name in Requisition.

- src/main/kotlin/org/wfanet/measurement/loadtest/config/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/config/TestIdentifiers.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
Testing EventGroups are identified by a reference ID prefix. The EventGroups created by EdpSimulator use this prefix. This helps prevent other EventGroups from interfering with the correctness test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/780)
> Only use testing EventGroups for CMMS correctness test.

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupMetadataDescriptorReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroupMetadataDescriptor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupMetadataDescriptorsServiceTest.kt
- src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptor.proto
- src/main/resources/kingdom/spanner/add-event-group-metadata-idempotency-key.sql
- src/main/resources/kingdom/spanner/changelog.yaml
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt
This allows for idempotent create operations.
This is for #768 and depends on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/785)
> Support request_id field in CreateEventGroupMetadataDescriptorRequest.

- src/main/k8s/local/kingdom.cue
This updates the local deployment configuration to match the dev one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/790)
> Specify the number of threads for local Kingdom gRPC servers.

- .github/workflows/build-test.yml
- .github/workflows/lint.yml
- src/main/k8s/local/emulators.cue
- src/test/kotlin/org/wfanet/measurement/integration/k8s/CorrectnessTest.kt
* Shut down Bazel server before correctness test run to save on RAM.
* Update to newer actions versions to avoid deprecation.
* Disable verbose gRPC logging on storage server to reduce log size to save.
* Tighten test method timeouts to decrease the likelihood of total test timeout.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/806)
https://rally1.rallydev.com/#/?detail=/defect/676017081901&fdp=true
> Re-enable K8s correctness test in Build and test workflow.

- .github/workflows/build-test.yml
There was a previous misconfiguration in an attempt to get the cache to save only if the correctness test passes, but the action is configured to only save when the all targets wildcard is used (`//...`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/826)
> Fix Bazel build output not being saved to Actions cache.

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This PR should fix https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/808
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)
> Correct noised reach calculation in fulfillDirectReachAndFrequencyMeasurement in EDP simulator

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt
This addresses flakiness in SpannerExchangeStepsServiceTest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/830)
> Use consistent time source for ExchangeStepAttempt ExpirationTime.

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderCertificateKey.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/DuchyCertificateKey.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/MeasurementConsumerCertificateKey.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/ModelProviderCertificateKey.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EncryptionKeyPairStore.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
Correlated lists are fragile and generally should not be used. This replaces some of the usage with maps. It also uses actual certificates/signatures to make the test more accurate.
This is pre-factoring for DataProvider public key signature verification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/824)
> Reduce usages of correlated lists in ReportsServiceTest.

- src/main/resources/kingdom/spanner/changelog.yaml
- src/main/resources/kingdom/spanner/create-measurements-by-token-index.sql
This replaces the unused MeasurementsByState index in order to avoid a full table scan for the StreamActiveComputations system API method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/844)
Depends on #843.
For #840.
> Create MeasurementsByContinuationToken database index.

- .github/workflows/build-test.yml
This allows correctness test results to be cached so that the test is not re-run if no dependencies have changed. The downside is that we do not get streaming test output, but the test timeouts should make that unnecessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/851)
> Include the correctness test in the "all targets" step.

- src/main/k8s/base.cue
- src/main/k8s/dev/base_gke.cue
- src/main/k8s/kingdom.cue
This fixes metrics only being collected for pods with permissive egress rules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/849)
> Add egress to OpenTelemetry collector on GKE network policies.

- src/main/k8s/kingdom.cue
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
The Certificates service needs to be callable using Duchy credentials. The auth checks are already in place, but the configuration file was not loaded.
Fixes #855
> Load DuchyCertConfig in public API server.

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidationException.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
The requisition was being logged as refused, but not actually refused.
> Refuse requisition from EDP simulator when filter is invalid.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt
From observations on QA, Spanner does not pick up this index automatically. Use of this index drops rows scanned for a StreamActiveComputations call from 1,919 to 217.
> Force MeasurementsByContinuationToken index for COMPUTATION view.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This also stops populating the liquid_legions_v2 field in Measurement.Details.protocol_config for these Measurements. As a result, the deprecated liquid_legions_v2 field in the ProtocolConfig message of the public API will no longer be populated.
This was missed in #861.
Fixes #869.
https://rally1.rallydev.com/#/?detail=/defect/687779117107&fdp=true
> Stop inserting ComputationParticipants rows for single-EDP R/F Measurements.

- build/repositories.bzl
removes the requirement that root certs must have AKIDs to be trusted.
Fixes #881
> update common-jvm version

- src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt
This adds api tests for the following ComputationsService RPCs:
* DeleteComputation
* PurgeComputations
* GetComputationToken
* UpdateComputationDetails
* AdvanceComputationStage
> Add more ComputationsService tests

- src/main/kotlin/org/wfanet/measurement/common/api/ResourceKey.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupMetadataDescriptorsServiceTest.kt
This avoids setting external_data_provider_id in the internal filter when the parent field in the request uses the wildcard character for the DataProvider ID. This also improves error messaging in upstream Reporting ListEventGroups calls.
Fixes #891
> Handle wildcard DataProvider in BatchGetEventGroupMetadataDescriptors.

- src/main/resources/kingdom/spanner/create-measurement-schema.sql
Liquibase changesets must remain immutable to avoid failing validation. This includes comments.
Fixes #903.
> Revert changes to create-measurement-schema.sql from e4c1e242f94c961e3379f35b2cdca04ef2dee1d0

- src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/ComputationTokenProtoQuery.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt
- src/main/kotlin/org/wfanet/measurement/duchy/service/internal/computations/ComputationsService.kt
- src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ComputationsServiceTest.kt
- src/main/proto/wfa/measurement/internal/duchy/BUILD.bazel
- src/main/proto/wfa/measurement/internal/duchy/computation_token.proto
This also stops setting LockExpirationTime on Computation creation.
This will allow a Mill act on lock information, for example timing out processing as soon as the lock expires.
> Include lock owner and expiration in ComputationToken.

- .bazelrc
- src/main/proto/wfa/measurement/config/reporting/metric_spec_config.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
* Make all fields in metric spec not required. Document the usage.
* Incorporate the new kingdom measurement design.
* Add metric spec config for storing default values.
> V2alpha DP params API

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderRequiredDuchies.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt
Create ReplaceDataProviderRequiredDuchies class to update duchy list in DataProviderRequiredDuchies table. The return value of the TransactionScope.runTransaction method in this class is the DataProvider object with the updated duchy list
Implement replaceDataProviderRequiredDuchies in SpannerDataProvidersService to call the new ReplaceDataProviderRequiredDuchies class with the ReplaceDataProviderRequiredDuchiesRequest. This method will throw an error if the externalDataProviderId is not present in the request.
Create test that checks:
1. the returned DataProvider has the updated duchy list
2. the DataProviderRequiredDuchies table is updated
https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342533129
> Implement logic to update Data Provider duchy list

- src/main/k8s/local/README.md
- src/main/proto/wfa/measurement/integration/k8s/testing/BUILD.bazel
- src/main/proto/wfa/measurement/integration/k8s/testing/correctness_test_config.proto
- src/main/proto/wfa/measurement/integration/k8s/testing/forwarded_storage_config.proto
- src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/integration/k8s/ForwardedStorageCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/correctness_test_config.tmpl.textproto
- src/test/kotlin/org/wfanet/measurement/integration/k8s/forwarded_storage_config.tmpl.textproto
This allows running the K8s correctness test against a running CMMS instance, with the following conditions:
* The instance uses the testing certificates/keys from the codebase.
* The EDP simulator sketches are accessible via a server which implements the ForwardedStorage service.
> Add ForwardedStorageCorrectnessTest.

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto
- src/main/resources/reporting/postgres/create-v2-reporting-schema.sql
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
Motivation:
* In the current design, the metric state is updated using a on-demand strategy -- only updated when the public `get` or `list` is called. This causes the internal metric state is not consistent with what the states of the associated measurements indicate. For example, a metric might have all measurements with SUCCEEDED states, but itself is PENDING. 
Design change:
* The metric state is essentially a derivative from the states of the associated measurements. Therefore, we could instead determine the metric state in the public server call and remove the state column in the internal metrics DB.
* Similarly, the metric result can be calculated easily on the public side, so we don't need to store metric result in the database.
> Derive metric states

- build/variables.bzl
- src/main/proto/wfa/measurement/integration/k8s/testing/BUILD.bazel
- src/main/proto/wfa/measurement/integration/k8s/testing/google_cloud_storage_config.proto
- src/test/kotlin/org/wfanet/measurement/integration/k8s/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/integration/k8s/GcsCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/gcs_config.tmpl.textproto
This allows running the K8s correctness test against a running CMMS instance, with the following conditions:
* The instance uses the testing certificates/keys from the codebase.
* The EDP simulator sketches are accessible via a Google Cloud Storage bucket.
https://rally1.rallydev.com/#/?detail=/task/697342182701&fdp=true
> Add GcsCorrectnessTest.

- .bazelrc
- .github/workflows/configure-duchy.yml
- .github/workflows/configure-kingdom.yml
- .github/workflows/create-cmm-images.yml
- .github/workflows/export-image-tag.sh
* //src/main/docker:push_all_gke_images target for push image workflow
* Kustomize-based targets for K8s workflows.
> Use new build targets for release workflows.

- .github/workflows/configure-duchy.yml
- .github/workflows/configure-reporting.yml
- .github/workflows/configure-simulators.yml
The following variables can be removed:
* DUCHY_STORAGE_BUCKET
* SIMULATOR_STORAGE_BUCKET
* REPORTING_CLUSTER_LOCATION
* POSTGRES_REGION
> Consolidate GitHub Environment variables.

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FrequencyDistributionSubject.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FuzzyLongSubject.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/MeasurementResultSubject.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
- src/test/kotlin/org/wfanet/measurement/api/v2alpha/testing/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/api/v2alpha/testing/MeasurementResultSubjectTest.kt
This makes correctness test failure messages more clear.
> Add MeasurementResultSubject Truth extension.

- src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt
The current slice of the test data set is small enough that the noise sometimes puts the value outside of the expected range. Increasing the time range reduces the flakiness of the test.
> Increase the time range for the correctness test.

- src/main/k8s/dev/base_gke.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/edp_simulator_gke.cue
- src/main/k8s/dev/kingdom_gke.cue
- src/main/k8s/dev/reporting_gke.cue
- src/main/k8s/dev/resource_requirements.yaml
- src/main/terraform/gcloud/cmms/duchies.tf
- src/main/terraform/gcloud/cmms/kingdom.tf
- src/main/terraform/gcloud/cmms/simulators.tf
This also follows best practice of setting request.memory == limit.memory, as memory is an incompressible resource.
> Update dev resource requirements based on observed usage.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelLinesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelLineReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ModelRolloutReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelLine.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRollout.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetModelLineHoldbackModelLine.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ModelLinesServiceTest.kt
- src/main/resources/kingdom/spanner/changelog.yaml
- src/main/resources/kingdom/spanner/update-vid-model-foreign-keys-and-indexes.sql
This PR introduces missing UNIQUE INDEXES for VID models related tables and also fix FOREIGN KEYS. They were not using the whole PRIMARY KEY.
> Add Unique indexes on VID models tables

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaultsTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
Refactor the code that processes user-defined metric spec. The extension method of `MetricSpec` takes as input the metric spec config and fills all optional fields underneath if they are unset.
> Add MetricSpecBuilder.

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/ExchangeKey.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/Providers.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Assertion.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangeStepsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ExchangesServiceTest.kt
- src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/exchanges_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangesServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RecurringExchangesServiceTest.kt
This also exposes the Exchanges and RecurringExchanges services in the public API server. Since these services were never exposed, this is not a breaking change.
> Ignore party field in public API GetExchangeRequest.

- build/repositories.bzl
> Fix cross-media-measurement-api repo target to use version.

- src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel
- src/main/kotlin/org/wfanet/panelmatch/common/BUILD.bazel
- src/main/kotlin/org/wfanet/panelmatch/common/certificates/BUILD.bazel
- src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/BUILD.bazel
- src/main/kotlin/org/wfanet/panelmatch/common/storage/BUILD.bazel
In general Bazel targets should follow "strict deps", meaning each target includes all dependencies that are used without relying on transitive dependencies. This prevents errors when transitive dependencies change. Eventually this will be enforced by Kotlin rules.
Furthermore, Bazel targets should not include unused deps. This prevents unnecessary rebuilding of targets.
> Remove unused dependencies from //src/main/kotlin/org/wfanet/panelmatch/common.

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupKey.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MeasurementsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/event_groups_service.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
This takes advantage of the secondary resource pattern for EventGroups in the CMMS API.
> Update EventGroup resource pattern in Reporting v2 API.

- src/main/resources/kingdom/spanner/update-vid-model-foreign-keys-and-indexes.sql
Without batch DDL, this changeset takes minutes to apply resulting in the update workflow timing out.
> Use batch DDL for update-vid-model-foreign-keys-and-indexes.sql.

- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/synthetic_generator_config_files_kustomization.yaml
- src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue
- src/main/k8s/testing/data/synthetic_event_group_spec_3.textproto
- src/main/terraform/gcloud/cmms/duchies.tf
- src/main/terraform/gcloud/cmms/simulators.tf
This is used in the dev K8s configuration. It is not used in local tests due to CI memory constraints.
> Add a larger-scale SyntheticEventGroupSpec.

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/InMemoryEventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/LabeledEvent.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SketchGenerator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel
- src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/person.proto
- src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGenerationTest.kt
Every field on an event message should use a message type that has an event_template annotation, and every field on a template message should have a template_field annotation.
> Remove non-template fields from our test templates.

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapperTest.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
Update EDP simulator to support ACDP composition. Currently keep using the old DP_ADVANCED composition with MPC Geometric(Laplace) noise and direct Laplace noise for backward compatibility. Once MPC DP noise is switched to Discrete Gaussian noise in Kingdom, and direct DP noise is switched to Gaussian in EDP simulator, change compositionMechasnim to ACDP and start using ACDP composition in PBM. 
ACDP composition can only be used with MPC discrete Gaussian or direct Gaussian noise. Otherwise, the requisition will be refused. The old DP_ADVANCED PBM ledger and composition methods, old PrivacyBucketCharges BackingStore table should be deprecated/deleted after migration to ACDP is completed/stabilized.
Major changes in this PR:
* Create a new CompositionMechasnim flag(DP_ADVANCED, ACDP) in …
> EDP simulator supports ACDP composition

- src/main/k8s/base.cue
This should prevent some unnecessary pulls when the image is unchanged.
> Stop defaulting imagePullPolicy on K8s Jobs to `always`.

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/GaussianNoiser.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/LaplaceNoiser.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/Noiser.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
This is the first part of the error bar implementation. In this PR, the variance calculations for different measurements are introduced. In the next PR, we will use them to compute the variances for different metrics in the reporting server.
> Measurement statistics calculation

- .bazelrc
- src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/GCloudPostgresInProcessLifeOfAMeasurementIntegrationTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/GCloudSpannerInProcessLifeOfAMeasurementIntegrationTest.kt
- tools/bazel-container
* Ensure TestContainers Ryuk is always disabled.
* Stop using CoroutinesTimeout in order to avoid Kotlin/kotlinx.coroutines#3865.
> Attempt to address flakiness in integration tests.

- docs/operations/enabling-gaussian-noise-and-acdp-pbm.md
Rally task link: https://rally1.rallydev.com/#/?detail=/task/720480906829&fdp=true
> Create Gaussian noise and ACDP composition rollout doc

- build/repositories.bzl
- src/main/k8s/kingdom.cue
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/Noiser.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt
- src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/direct_computation.proto
- src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
In this PR, the implementation of the [API changes in CMM-API](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/163) is done. The main changes are 
1. new direct protocol config,
2. additional info in measurement results, and
3. new enum constants in `ProtocolConfig.NoiseMechanism`. 
4. EDP simulator choose the noise mechanism based on the overlap of its preferences and the noise mechanism options in the direct protocol config.
Any future measurement creations will contain certain direct protocol configs based on the measurement types. For the backward compatibility for existing measurements and requisitions, the empty internal direct protocol configs will be converted with the options that would have been valid at the time the Measurement was created. …
> Circulate direct computation methodology from protocol config to measurement result.

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto
- src/main/resources/reporting/postgres/add-binary-representation-column-to-weighted-subset-unions-and-metric-measurements.sql
- src/main/resources/reporting/postgres/changelog-v2.yaml
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt
Part of the changes for implementing error bars in reporting server. To easily find the union of any two weighted measurements in a metric, we store the binary representation of each measurement from the binary representation of the weighed subset union created during set expression compilation of a reporting set.
> Store set operation compilation IDs

- src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto
- src/main/k8s/testing/secretfiles/ro_llv2_protocol_config_config.textproto
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerTest.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
Roll out Gaussian noise and ACDP composition by changing the default values of `noise_mechanism` to `DISCRETE_GAUSSIAN` in testing configs for the LLV2 protocols, and `compositionMechanism` to `ACDP` in EDP simulator. By changing `noise_mechanism` to `DISCRETE_GAUSSIAN`, Duchy will add discrete Gaussian noise distributedly to MPC measurements. And by changing compositionMechanism to ACDP, PBM in EDP simulator will use ACDP composition for privacy accounting, and EDP simulator will add continuous Gaussian noise to direct measurements.
The changes will be effective in the Halo QA environment as well as in InProcessLifeOfAMeasurementIntegrationTest and EmptyClusterCorrectnessTest.
Rally task link: https://rally1.rallydev.com/#/?detail=/task/720480912395&fdp=true
> Enable Gaussian noise and ACDP composition

- experimental/reporting-ui/src/main/react/reporting-ui/client/reporting/testing/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/client/reporting/testing/webpack.config.js
- experimental/reporting-ui/src/main/react/reporting-ui/component/card_wrapper/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/component/card_wrapper/card_wrapper.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/index.css
- experimental/reporting-ui/src/main/react/reporting-ui/index.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/public/index.html
- experimental/reporting-ui/src/main/react/reporting-ui/util/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/util/formatting.ts
- experimental/reporting-ui/src/main/react/reporting-ui/util/numberWithMagnitude.ts
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/header.css
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/header.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/overview.css
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/overview.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/overview_card.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/publisher_cell.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/summary_table.css
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/summary_table.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/summary_table_row.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/component/terminal_report.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report/report_view.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view_model/report/report_view_model.ts
Adding components to the Report view:
* Header
* Summary Cards
* Summary Table
Graphs will come as a follow up PR.
> adding header, cards, and table to Report view

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt
- src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt
- src/main/proto/wfa/measurement/internal/duchy/computation_details.proto
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt
> Use participant count instead of gRPC stubs count in LLv2 mills.

- src/main/k8s/kingdom.cue
- src/main/kotlin/org/wfanet/measurement/kingdom/batch/CompletedMeasurementsDeletion.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/job/CompletedMeasurementsDeletionJob.kt
Added a flag to control the number of measurements to delete in each delete RPC.
https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1199
https://rally1.rallydev.com/#/?detail=/defect/721441730037&fdp=true
> Updated measurement retention job to have a flag to control maximum number of measurement to delete

- src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/Flows.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PublicKeysServiceTest.kt
> Fix internal GetMeasurementConsumer possibly returning incorrect Certificate.

- .github/workflows/build-test.yml
This ensures that the build for the pull request can use the latest build cache.
> Wait for build to complete on main branch before running on PR.

- build/repositories.bzl
This picks up an update to Java base images.
> Update common-jvm to 0.65.0.

- src/main/k8s/kingdom.cue
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/RoLlv2ProtocolConfig.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
This also removes the flag from the Kingdom internal API server since it is not read there.
> Enable reach-only LLv2 protocol in local and dev configurations.

- src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt
s3FromBeam can have unintended consequences and today doesn't play nice with other code that assumes roles. This will need further fixing in the future once we move to executing beam jobs in a distributed environement.
This also fixes an issue where we assume beam options always returns a non-nullable String. However, sometimes, it is null.
> s3fromBeam should be false by default

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/SetMeasurementResults.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MeasurementsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/BUILD.bazel
- src/main/proto/wfa/measurement/internal/reporting/v2/direct_computation.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/measurements_service.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/mpc_protocol.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/noise_mechanism.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
In addition to storing results in the internal measurements, we also store the computation details about the measurement creation. The structure of the internal measurement result is now same as the one in Kingdom -- measurement results are in a list to represent results from different data providers; noise mechanisms and computation methodologies are added to `Result`. Note that unlike the Kingdom `Result` which stores only direct noise mechanisms and direct methodologies, here we store both direct and MPC noise mechanisms and methodologies.
The additional computation details can be used to compute measurement variances and potentially used to identify measurements. No DB change is needed as the changes happened in `Details`.
> Store measurement computation details in reporting for error bars

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
This pull request introduces a validation check for frequency histogram metrics to ensure they are only computed on union-only set expressions. It also updates the unit test name of when a reporting set is not accessible to the caller and adds a test case for the new validation check.
1. In `MetricsService.kt`, a validation check was added to ensure that frequency histogram metrics are only computed on union-only set expressions. If this condition is not met, an `INVALID_ARGUMENT` error is thrown.
2. The name of the test case `createMetric throws INVALID_ARGUMENT when reporting set is not accessible to caller` was updated to `createMetric throws PERMISSION_DENIED when reporting set is not accessible to caller`.
3. A new test case `createMetric throws INVALID_ARGUMENT when Frequency …
> Restrict metric set operations based on metric types

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
This pull request fixed the filter list creation in the MetricsService class.
> 
Remove the filter of measurement's primitive reporting set basis from filter list creation.
>
The filter list creation was previously done by concatenating the filter list from a measurement and the filter from the measurement's primitive reporting set basis. However, the filter from latter should already be included in the former.
> Remove duplicate filter during event group entry creations

- src/main/proto/wfa/measurement/reporting/v2alpha/report.proto
Allow for an event filter on MetricCalculationSpec so that ReportingSets can be used without filters. This is in response to a request from @mariolamassaavedra.
> Adds an event filter to MetricCalculationSpec.

- src/main/proto/wfa/measurement/reporting/v2alpha/report.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto
Tags are a map of key-value pairs of strings intended to help UIs and other rich clients make connections between display artifacts and reporting artifacts without having to write code to interpret the structure of reports or reporting sets.
> Adds key-value pair tags to Report and ReportingSet.

- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
* Rename `*VarianceParams` to `*MeasurementVarianceParams` to better distinguish from `*MetricVarianceParams` later.
* Store `VidSamplingInterval` instead of just `vidSamplingIntervalWidth` in `*MeasurementParams` for later use in covariance calculations.
> Refactor MeasurementStatistics

- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
This pull request changes the data type of `Reach` and `Impression` variables from Int to Long in multiple functions and test cases within the code. 
- The change to the data type of the "totalReach" variable from Int to Long allows for larger values to be used in the computation of variances.
- Updating the data classes to use Long data types instead of Int for certain variables ensures consistency and accuracy in the computation of variances.
- The change improves the precision and accuracy of the computations, especially when dealing with large reach values.
> Refactor Int type to Long type in MC stats library

- .github/workflows/api-lint.yml
- .github/workflows/build-test.yml
- .github/workflows/lint.yml
This is in preparation for using release branches to create patch (AKA "bugfix") releases.
> Apply pre- and post-submit workflows to release branches.

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/direct_computation.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
This pull request is the implementation of [this API change]([url](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/178)). 
- Modification of the "customDirectMethodology" property in the "EdpSimulator" class, changing the "variance" property to "scalar" and setting its value to 0.0.
- Function to convert a CustomDirectMethodology object to an InternalCustomDirectMethodology object.
- Addition of a new message called "CustomDirectMethodology" in the internal "direct_computation.proto" file, including a "FrequencyVariances" message with two maps for storing variances of frequency distributions and a "variance" field to store the variance of the result computed from the custom direct methodology.
- Test cases in the "MetricsServiceTest.kt" file, checking …
> Implement refactoring of custom direct methodology

- docs/operations/updating-release.md
This ensures that old Deployments that were renamed are pruned.
> Mention `--prune` option when updating.

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsServiceTest.kt
This removes a workaround that is no longer needed now that the REACH Measurement type has been released.
Note that this only affects the REACH_AND_FREQUENCY Measurement type. The R/F LLv2 protocol can still be used with a max frequency of 1 in lieu of the reach-only LLv2 protocol for the REACH Measurement type.
> Require maximum_frequency for REACH_AND_FREQUENCY Measurements to be > 1.

- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/StatsExceptions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
Implementing metric variances for different metric types. This includes:
* A function to compute the covariance of two reach measurements based on their methodologies.
* Unifying functions to compute variances of frequency count to one function.
* Functions to compute measurement variances based on the methodologies.
* Functions to compute metric variances based on the composition of their weighted measurements.
* Changing the type of `SketchSize` and `SamplingIndicatorSize` from `Double` to `Long`.
> Add metric variance calculations

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt
> Marcopremier fix confirmcomputationparticipant

- build/repositories.bzl
This fixes compilation on more recent compiler configurations.
> Update common-cpp to 0.10.1.

- .github/workflows/build-test.yml
This fixes PRs based on release branches waiting for `main` instead of the release branch.
> Do not assume that base branch is always `main` when waiting for build.

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This should make it clearer to real EDP integrators that they need to use the matching private key.
> Verify that EdpData signing key matches certificate in Requisition.

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/report.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/report.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
An addition filter was added to `MetricCalculationSpec` in #1250.  This PR further added the filter to `MetricCalculationResult` and implements the API changes.
> Add additional filter to MetricCalculationSpec

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/reporting_set.proto
- src/main/resources/reporting/postgres/add-details-column-to-reporting-sets.sql
- src/main/resources/reporting/postgres/changelog-v2.yaml
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingSetsServiceTest.kt
This PR implements the tags field which was added to `ReportingSet` in #1251. A change to the DB schema is needed.
> Add reporting set tags

- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingExceptions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
Compute metric variances in a report using the `Variances` library. Any insufficiency of inputs to the variance calculation will not set `univariate_statistics`.
* Reach: compute variances from weighted reach measurements.
* Frequency histogram: compute variances from weighted reach and frequency measurements.
* Impression count: compute variances only when the operation is union-only. The variance of an impression metric is the sum of the weighted impression results.
* Watch duration: compute variances only when the operation is union-only. The variance of a duration metric is the sum of the weighted duration results.
> Add metric variances to metric results in reporting v2

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystem.kt
- src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt
The field has been deprecated since v0.4.0.
> Stop setting deprecated event_groups field in RequisitionSpec.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt
The EventGroupDetails column in the EventGroups table is nullable, and GetEventGroup correctly handles the null case by not having the details field set in the EventGroup message. DeleteEventGroup was incorrectly setting both the column and the response value to an empty EventGroup.Details.
> Fix internal DeleteEventGroup not clearing details.

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresMeasurementsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateMeasurements.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/MeasurementsServiceTest.kt
- src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
I tested a Report that created 300 measurements using a PeriodicTimeInterval with 300 increments. On a GKE cluster (e2-standard-2), it originally took ~60 seconds. With this PR, it takes ~30 seconds. Adding BatchCreateMeasurements to the internal Reporting server led to the bulk of the improvement. Caching the GetDataProvider and GetCertificate calls didn't lead to a large improvement. The measurement creation flow (Create Kingdom Measurements -> Create Reporting Measurements) occupies the bulk of the time. The only thing I could think of to further improve the performance is to add BatchCreateMeasurements to the Kingdom Public API.
> Improve Performance of Measurement Creation in Create Report

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FrequencyDistributionSubject.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FuzzyLongSubject.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
Using variances instead of fixed tolerance values for checking measurement values. 
- Add a `isWithin` function to compare actual and expected using a tolerance map.
- Add a function to compute reach variances.
- Add a function to compute the margin of error of a 99.9% Confidence Interval (CI).
- Add a function to compute tolerances for relative frequency results.
- Check if reach results and frequency results are within 99.9% CI. 
Previous checks on measurement results were using fixed tolerance values which is hardcoded and not meaningful. Using CIs provides a statistical way to make sure that the noised results fall into a reasonable range.
> Use Variance library to calculate tolerances in Measurement tests

- src/main/k8s/testing/data/synthetic_population_spec.textproto
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEventQuery.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MetadataSyntheticGeneratorEventQuery.kt
- src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This allows overriding the event message used by the EDP simulator when using the synthetic generator event source. This is done by specifying the `event_message_type_url` field in `SyntheticPopulationSpec` and the `--event-message-descriptor-set` command-line option for the EDP simulator.
> Support arbitrary event message types for synthetic event generation.

- src/main/k8s/panelmatch/testing/workflows/mini_exchange_workflow.textproto
- src/main/k8s/testing/secretfiles/exchange_workflow.textproto
The export step requires a certificate resource to be present to attach to the `NamedSignature`.
In some exchanges, this value will be pre-computed before the exchange. However, if the exchange, itself, generates a certificate, then any export step should depend on the output of that step to ensure the export doesn't run before the certificate is present.
> depend on output of generate_certificate_step in any export step

- build/repositories.bzl
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportingExceptions.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/direct_computation.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
This PR accommodate the API change from [cmm-api PR186](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/186) that allows EDPs not to provide variances of custom direct methodology instead a reason.
In addition to the changes due to refactoring, there are two main changes:
1. If the reason of not having variance in custom direct methodology is not specified, raise error.
2. If the variance field in custom direct methodology is not set, raise error.
3. MetricsService will not set `UnivariateStatistics` when the custom direct methodology has no variance with a reason.
> Allow custom methodology not to provide variance but with a reason

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClippingTest.kt
* For impression/duration measurements, we have to set an impression/duration cap to guarantee differential privacy
* Currently, the measurement consumers(MC) select the cap, but it's challenging for MCs since the optimal cap should be chosen based on the frequency/duration distribution
* The Dynamic Clipping library allows the EDP to automatically optimize the cap for each campaign and to achieve higher accuracy than using a fixed cap, based on the frequency distribution of the events
The Dynamic Clipping library is provided as a reference implementation for EDP to potentially improve impression/duration measurement accuracy. It is an optional EDP feature, and will require additional local market approval for deployment in production. …
> Create Dynamic Clipping library for impression measurement

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This addresses an issue where the EDP simulator may output a "sparse" relative frequency distribution for the Direct protocol where not all buckets are included.
> Output a dense frequency distribution for Direct protocol.

- src/main/terraform/gcloud/cmms/duchies.tf
- src/main/terraform/gcloud/examples/duchy/main.tf
These machines are compute-optimized and more readily available across regions. They are also cheaper in terms of current spot VM pricing.
> Use C2 machines by default for LLv2 Mills on GKE.

- src/main/k8s/testing/secretfiles/metric_spec_config.textproto
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt
- src/main/proto/wfa/measurement/config/reporting/metric_spec_config.proto
- src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto
- src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
- src/main/resources/reporting/postgres/create-v2-reporting-schema.sql
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaultsTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
In Report V2 the `FrequencyHistogramParams` will be renamed to `ReachAndFrequencyParams`. Note the `FrequencyHistogramParams` already includes `ReachParams`. Setting this new Params structure cause a Reach and Frequency Results to be created. As such, metric result for `ReachAndFrequency` will be updated to replace `HistogramResult` with a `ReachAndFrequencyResult` that includes a `HistogramResult` and a `ReachResult` as sub-messages.
Note:
* This PR changes an existing Liquibase changeset, meaning the DB will need to be wiped.
* This PR renames a field in `MetricSpecConfig`, so anyone with an existing deployment will need to update their config.
Report V1 will not be updated.
> Refactor reach-and-frequency metric

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt
Given the fact that `MetricCalculationSpec` is now an individual resource and can be reused, we can utilize this to identify a set of metrics across reports. Note that the granularity is "a set of metrics" that is associated with `MetricCalculationSpec`.
When a `MetricCalculationSpec` is reused in a different report, by identifying the pair of `MetricCalculationSpec` and the `ReportingSet` and the `TimeInterval`s from the report, we are able to identify the existing set of metrics created from the previous reports. This could be done during the internal report creation by the following:
1. Left join the table `Metrics` and `MetricCalculationSpecReportingMetrics` by `MeasurementConsumerId` and `MetricId`.
2. Find the set of metrics given `MeasurementConsumerId`, `ReportingSetId`, …
> Add a metric reuse mechanism based on timed ReportingMetricEntries

- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/postgres/writers/FinishComputation.kt
This is similar to a fix (#1238) that was applied to the Spanner implementation.
> Postgres: Fix Mill infinite retry if Computation is already failed

- experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/service/api/v1alpha/ReportsService.kt
Supposed to use `tagsMap` instead of `tags`
Verified the warning. Verified the warning was resolved.
Also cleared bazel cache. Not clearing sometimes hid the warning.
> fix java deprecated build waring

- .github/workflows/build-test.yml
- .github/workflows/push-images.yml
rules_oci outputs additional layer blobs that result in the Bazel cache being too large. See https://github.com/bazel-contrib/rules_oci/issues/439
> Fix Bazel cache trimming for rules_oci blobs.

- experimental/reporting-ui/src/main/react/reporting-ui/view/report_list/component/BUILD.bazel
- experimental/reporting-ui/src/main/react/reporting-ui/view/report_list/component/header.css
- experimental/reporting-ui/src/main/react/reporting-ui/view/report_list/component/header.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/view/report_list/report_list_view.tsx
- experimental/reporting-ui/src/main/react/reporting-ui/webpack.config.js
Add a header to the list reports view. Not using the same one from get reports since most of the icons don't make sense. Also making it easier to modify when we get some style updates.
Fixing the react-router browser router. It wasn't working when you refresh the page (other than the root) and would fail if you directly navigate to a sub-link.
> update list view style and fix some UI problems

- build/repositories.bzl
This fixes stack traces not being included in structured logging.
> Update common-jvm dep to 0.71.2.

- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt
The current CoroutineLauncher has not limit on the number of coroutines it launches. This works well on a platform like DataflowRunner but performs poorly with the DirectExecutor. This PR
1. Adds a parameter to specify the max number of jobs that should be executed in parallel with the CoroutineLauncher.
2. Sets the max number of jobs to 1 for the Aws example daemon.
> add maxCoroutines parameter to CoroutineLauncher

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
This is a fix PR for #1384. In this PR, 
1. fix the frequency normalization in `MeasurementResults.computeReachAndFrequency` by early returning when reach is 0.
2. Round the noise added to the frequency histogram during the process of noising frequency distribution.
3. cap negative values to 0 for direct reach and frequency.
4. fix the frequency normalization.
5. adding new unit test to capture the case when direct reach is 0.
> Fix normalizing frequency distribution

- src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilter.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketMapper.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AlwaysChargingPrivacyBucketMapper.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/config/PrivacyBudgets.kt
- src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketFilterTest.kt
This is needed for Origin since their event templates do not have fields corresponding to normal demographic privacy buckets (age, gender)
> cherry pick always charging privacy bucket mapper

- WORKSPACE
- build/versions.bzl
The version compatibility should ideally be handled by Maven artifact resolution (meaning google-api-services-storage < 2 should require google-api-client < 2). Alas it is not, so this works around the issue by specifying the version explicitly.
Closes #1410
> Update google API clients for compatibility with google-api-client.

- src/main/k8s/base.cue
This reduces the container overhead for non-JVM memory.
> Default MALLOC_ARENA_MAX to 2.

- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProvider.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProviderTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
This allows CelEnvProvider to be used for multiple Reporting API versions.
Fixes #1406
> Pass Reporting EventGroup message descriptor to CelEnvProvider impls.

- src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue
- src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto
- src/main/terraform/aws/modules/eks-cluster/main.tf
- src/main/terraform/gcloud/cmms/reporting.tf
- src/main/terraform/gcloud/cmms/simulators.tf
- src/main/terraform/gcloud/modules/reporting/main.tf
* Update default LLv2 protocol configuration including larger sketch size.
* Update corresponding memory limits to handle this.
* Allow Reporting v2 to be deployed alongside Reporting v1 in the same cluster.
> Update configurations for demo Reporting UI.

- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/common/server/V1AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProvider.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/CelEnvProviderTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
This allows CelEnvProvider to be used for multiple Reporting API versions.
(cherry picked from commit 2306a1675585aa3139e3c38b79a28b19cd52a4a4)
> Pass Reporting EventGroup message descriptor to CelEnvProvider impls. (#1417)

- src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue
- src/main/k8s/local/edp_simulators.cue
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEdpSimulatorRunner.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
The `--event-group-spec` option of `SyntheticGeneratorEdpSimulatorRunner` can now be specified multiple times, taking a key-value pair of `EventGroup` reference ID suffix to `SyntheticEventGroupSpec` file path.
> Support creation of multiple synthetic generation EventGroups in EDP simulator

- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/InProcessServersMethods.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt
When running this in a Kubernetes Cron Job, the job isn't considered completed without this change.
> Shutdown threads properly so Report Scheduling Process can complete

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/MeasurementResultSubject.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
In this PR we added the implementation of the `DeterministicCount` impression to the EDP simulator and a method to compute an expected impression based on reached VIDs and maximum frequency.
For testing, the unit tests in `EdpSimulatorTest` use a known tolerance based on the designed parameters for checking impression results, whereas the integration test in `MeasurementConsumerSimulator` is using scaled standard deviation calculated by the measurement variance library as the tolerance.
> Add impression implementation to EDP simulator

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
Filtering right after the internal `batchCreateMetrics` would filter out existing metrics in terminal states. Do filtering separately for creating CMM measurements.
> Filtering should be done separately for creating measurements

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGeneration.kt
- src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/simulator_synthetic_data_spec.proto
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticDataGenerationTest.kt
This allows implementations to be deterministic and language-agnostic.
> Use hashing rather than RNG for VID sampling of synthetic events.

- src/main/k8s/panelmatch/dev/example_daemon_aws.cue
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncher.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt
- src/main/kotlin/org/wfanet/panelmatch/integration/ExchangeWorkflowDaemonForTest.kt
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/CoroutineLauncherTest.kt
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClientTest.kt
- add maxCoroutines parameter to CoroutineLauncher (#1383)
The current CoroutineLauncher has not limit on the number of coroutines
it launches. This works well on a platform like DataflowRunner but
performs poorly with the DirectExecutor. This PR
1. Adds a parameter to specify the max number of jobs that should be
executed in parallel with the CoroutineLauncher.
2. Sets the max number of jobs to 1 for the Aws example daemon.
cherry picked from 2c1bbc698d1e551901cee183f59bde8cb8f193b4
- 75b40ba: move exchange limiter to GrpcApiClient (#1392)
cherry-picked from 6702c271c17f83a516c39936b2c4c0f38936162e
- 97465bb: release semaphore if no exchange step is found (#1460)
cherry picked from 96b2ca37f3e82b0b9bfabf34c03b9abe6f93792b
> cherry pick 3 commits for max exchange steps parallel

- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/LiquidLegions.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MeasurementStatistics.kt
- src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
- src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
The variance calculation of frequency distribution will output `NaN` when reach is zero. Moreover, the estimated variance is not accurate when reach is impractically small. The solution is to check whether the reach is too small using its confidence interval. If the confidence interval of the reach contains values <= 0, we claim the reach is too small for an accurate variance estimate of frequency distribution, and output the variance of uniformly random draw from [0, 1].
> Output uniformly random guess at frequency distribution when reach is too small

- src/main/terraform/aws/modules/rds-postgres/main.tf
This avoids issues where the engine version is upgraded outside of Terraform, causing future Terraforming to fail unless engine_version is updated.
> Specify auto_minor_version_upgrade = false for AWS Postgres DB.

- .github/workflows/run-k8s-tests.yml
- src/main/kotlin/org/wfanet/measurement/common/ExponentialBackoff.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessReachMeasurementAccuracyTest.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/AbstractCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/BigQueryCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/SyntheticGeneratorCorrectnessTest.kt
When running against a test cloud environment, the sketch size and number of events means that R/F tests using LLv2 may take up to an hour.
> Increase test timeout for K8s test workflow.

- .github/workflows/configure-reporting-v2.yml
- .github/workflows/configure-reporting.yml
- .github/workflows/run-k8s-tests.yml
- .github/workflows/terraform-cmms.yml
- .github/workflows/update-cmms.yml
* Read MEASUREMENT_CONSUMER_CONFIG from secrets instead of vars.
* It contains the MC API key, which should be secret.
* Stop reading BigQuery vars for K8s tests.
> Clean up workflow access of environment vars/secrets.

- .github/workflows/configure-simulators.yml
> Fix configure-simulators workflow not setting google_cloud_project.

- MODULE.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt
- src/main/proto/wfa/measurement/internal/reporting/v2/direct_computation.proto
- src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
For API change in https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/197
> Update cross-media-measurement-api dep for CustomMaximumFrequencyPerUser in DeterministicCount methodology

- src/main/k8s/dev/bigquery_edp_simulator_gke.cue
- src/main/k8s/dev/duchy_eks.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/synthetic_generator_edp_simulator_gke.cue
This is to support the currently configured sketch size for LLv2.
> Increase Mill and EDP simulator memory sizes for dev configuration.

- docs/gke/correctness-test.md
- docs/gke/simulator-deployment.md
- src/main/k8s/dev/README.md
- src/main/terraform/gcloud/examples/simulators/README.md
- src/main/terraform/gcloud/examples/simulators/main.tf
- src/main/terraform/gcloud/examples/simulators/variables.tf
- src/main/terraform/gcloud/examples/simulators/versions.tf
- src/test/kotlin/org/wfanet/measurement/integration/k8s/BigQueryCorrectnessTest.kt
BigQueryEventQuery was updated to use the UK pilot event message in #1491.
> Update simulator guides to reflect BigQuery event source changes.

- src/main/k8s/dev/BUILD.bazel
This addresses a build breakage introduced in #1512
> Fix dev Duchy kustomization_dir targets not being marked as testonly.

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CancelMeasurement.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
The current implementation doesn't take advantage of batching and has separate reads for each create.
> Improve performance of batch create measurements

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/ReportingTest.kt
Update the Reporting CLI tool to create a UI readable report. It is moderately hardcoded to limit the amount of configuration required by the user. There are a number of steps to complete this process:
1. Create 3 primitive Reporting Sets (with a number of event groups).
2. Create 1 union Reporting Set - the union of all 3 primitives.
3. Create 3 unique Reporting Sets (difference between the union and the union of the other two. eg. unique A = ABC - BC)
4. Create 1 metric calculation spec for the primitives.
5. Create 1 metric calculation spec for the composites.
6. Create a report mapping the reporting sets and metric calculation specs and include the other report parameters (like date range and frequency).
All the reporting sets and the report will be tagged appropriately so the …
> Add CreateUiReport to the CLI

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/InternalStatusConversion.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeysServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PublicKeysServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This is to conform to AIP-193, which states:
> Keys must be expressed as lower camel-case.
> Fix casing of metadata keys in public API ErrorInfo.

- .github/workflows/configure-duchy.yml
This addresses an issue that was introduced in #1537
> Add missing define in Duchy workflow

- src/main/terraform/gcloud/modules/duchy/main.tf
- src/main/terraform/gcloud/modules/duchy/variables.tf
- src/main/terraform/gcloud/modules/kingdom/main.tf
- src/main/terraform/gcloud/modules/kingdom/variables.tf
Import of `google_compute_address` not sufficient to keep any existing IP addresses unless the resource can be updated in-place. Specifying the `address` field in addition will ensure the actual IP address remains reserved.
> Add variables for specifying existing IP addresses in gcloud Terraform modules.

- .github/workflows/deploy-nightly.yml
* Prefix with "nightly/".
* Use run attempt number instead of run number for suffix.
> Adjust Git tag format for nightly builds.

- src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachFrequencyLiquidLegionsV2MillTest.kt
- src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt
The PR is to fix issue https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1626
> Fix the bug that enqueues Computations in ending stage.

- src/main/terraform/gcloud/cmms/duchies.tf
- src/main/terraform/gcloud/cmms/kingdom.tf
- src/main/terraform/gcloud/cmms/reporting.tf
- src/main/terraform/gcloud/cmms/reporting_v2.tf
- src/main/terraform/gcloud/cmms/simulators.tf
- src/main/terraform/gcloud/examples/duchy/main.tf
- src/main/terraform/gcloud/examples/kingdom/main.tf
- src/main/terraform/gcloud/examples/simulators/main.tf
- src/main/terraform/gcloud/modules/cluster/outputs.tf
This avoids node pool recreation whenever any cluster config changes.
> Stop reading google_container_cluster after creation.

- MODULE.bazel
> fix: use version for common-jvm dep

- .github/workflows/configure-aws-duchy.yml
- .github/workflows/configure-duchy.yml
- src/main/k8s/base.cue
- src/main/k8s/dev/duchy_eks.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/duchy.cue
- src/main/k8s/local/duchies.cue
The name is too long for the standard metadata name field.
BREAKING CHANGE: Renames a K8s Deployment in the dev configuration.
> fix!: shorten overly long name for HMSS Mill Deployment

- .github/workflows/publish-maven-artifacts.yml
Unlike the `build` subcommand, the `run` subcommand of the Bazel CLI only operates on a single target.
> fix: publish all Maven artifacts, not just one

- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/ApiClients.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClient.kt
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/ApiClientsTest.kt
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/BUILD.bazel
- src/test/kotlin/org/wfanet/panelmatch/client/launcher/GrpcApiClientTest.kt
Creates a wrapper `ApiClient` that can perform the "max parallel claimed exchange step" logic and delegates to another client for all other logic.
This allows the Kingdom-less flow to support the max parallel steps flag trivially.
> Make max parallel claimed exchange step logic reusable.

- build/variables.bzl
- src/main/k8s/panelmatch/base.cue
- src/main/k8s/panelmatch/dev/BUILD.bazel
- src/main/k8s/panelmatch/dev/example_kingdomless_daemon_gke.cue
- src/main/k8s/panelmatch/dev/example_kingdomless_edp_daemon_gke.cue
- src/main/k8s/panelmatch/dev/example_kingdomless_mp_daemon_gke.cue
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt
- src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemon.kt
- src/main/kotlin/org/wfanet/panelmatch/client/launcher/KingdomlessApiClient.kt
- src/main/kotlin/org/wfanet/panelmatch/common/certificates/KingomlessCertificateManager.kt
Summary:
* Creates `.cue` files for deploying Kingdom-less daemon to GKE.
* Adds Kingdom-less daemon flags.
* Uses `@ArgGroup` to ensure mutual exclusitivity between Kingdom-based flags and Kingdom-less flags.
* Updates the example daemon main class to build the correct type of `ApiClient` and `CertificateManager` based on which group of flags was set.
* Several other tweaks to make the deployment work:
* Factory function for building a shared storage client needed to be `suspend`ing.
* Explicitly call `withDefaultCredentails()` when building `GcpKmsClient`. This used to happen by default, but seems to have been (inadvertently?) removed in a previous PR.
* In `KingdomlessApiClient.kt`:
* Make sure that `ExchangeWorkflowDependencyGraph` is built in step order. The dependency graph will …
> Prepare example Kingdom-less exchange daemon for GKE.

- src/main/terraform/gcloud/cmms/duchies.tf
- src/main/terraform/gcloud/examples/duchy/main.tf
After some testing, the aggressive scale down seems to be less desirable w.r.t. Mill startup latency. In addition, Pod logs are lost when a Node is removed.
> fix: switch Duchy cluster autoscaling profile back to BALANCED

- .github/workflows/build-test.yml
This was missed in #1689.
This includes an update to the build-test workflow to ensure the lockfile is up-to-date.
> fix: update Bazel lockfile

- src/main/k8s/dev/open_telemetry_gke.cue
- src/main/k8s/open_telemetry.cue
This avoids warnings about trace exporting not being supported.
> fix: don't export OpenTelemetry traces using prometheus exporter

- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/mill/MillJobScheduler.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/liquidlegionsv2/LiquidLegionsV2MillJob.kt
- src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/job/mill/shareshuffle/HonestMajorityShareShuffleMillJob.kt
- src/main/kotlin/org/wfanet/measurement/duchy/mill/MillBase.kt
- src/main/kotlin/org/wfanet/measurement/duchy/mill/MillFlags.kt
This checks that the work item has not changed since it was claimed and that the Mill instance currently holds the lock for the work item.
> fix: ensure Mill job should process claimed work item

- src/main/k8s/base.cue
- src/main/k8s/edp_simulator.cue
- src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/Health.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt
- src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt
This introduces a health check to the EDP simulator, where it is considered healthy only after its initialization items (e.g. updating capabilities). This is used by a Kubernetes startup probe.
Fixes #1728
> fix: Wait for EDP simulator to initialize before considering it ready

- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
The current threshold (3.291 x sigma) guarantees that each noisy measurement is 99.9% within the confidence interval. However, the integration tests consist of at least 30 independent noisy values. This pushes the failure rate to (1-0.999^30 ~ 0.03), which is a bit high and causes the presubmit test to be flaky. Increasing this threshold to 5 x sigma will bring the failure rate down to below 0.0001.
> test: Update confidence interval for integration tests.

- MODULE.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ComputationParticipantReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BatchCancelMeasurements.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CancelMeasurement.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateRequisition.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt
- src/main/proto/wfa/measurement/internal/kingdom/measurement.proto
- src/main/proto/wfa/measurement/system/v1alpha/requisition.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This sets the Requisition state to WITHDRAWN when a Measurement is cancelled or failed.
> feat!: Update cross-media-measurement-api dep for Requisition.State.WITHDRAWN

- docs/eks/duchy-deployment.md
- docs/eks/metrics-deployment.md
- docs/gke/duchy-deployment.md
- docs/gke/kingdom-deployment.md
- docs/gke/metrics-deployment.md
- src/main/k8s/base.cue
- src/main/k8s/dev/base_gke.cue
- src/main/k8s/dev/duchy_eks.cue
- src/main/k8s/dev/duchy_gke.cue
- src/main/k8s/dev/kingdom_gke.cue
- src/main/k8s/dev/open_telemetry_eks.cue
- src/main/k8s/dev/open_telemetry_gke.cue
- src/main/k8s/dev/reporting_gke.cue
- src/main/k8s/dev/reporting_v2_gke.cue
- src/main/k8s/open_telemetry.cue
The previous behavior was to add some default ingresses and egresses to every NetworkPolicy other than default-deny. The flaw with this behavior is that if no NetworkPolicy matches the pod, the pod will not have these default ingresses and egresses. This instead creates separate NetworkPolicy objects for defaults.
This also fixes an issue where the opentelemetry-collector NetworkPolicy was missing its pod selector and was therefore applying to all pods.
> fix!: Ensure default network policies are created

- src/main/terraform/aws/cmms/duchies.tf
- src/main/terraform/aws/examples/duchy/main.tf
The current 1.28 version will reach end of standard support on November 26, 2024. The latest available version is 1.30, but cluster version upgrades must be done one minor version at a time.
Unlike GKE, EKS does not appear to have support for automatic upgrades.
> chore: Update EKS clusters to 1.29 in Terraform configs

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeStepAttemptReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RecurringExchangeReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroupMetadataDescriptor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchange.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurements.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateRecurringExchange.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FinishExchangeStepAttempt.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/MeasurementLogEntries.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataAvailabilityInterval.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ReplaceDataProviderCapabilities.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroupMetadataDescriptor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdatePublicKey.kt
- src/main/resources/kingdom/spanner/changelog.yaml
- src/main/resources/kingdom/spanner/drop-json-columns.sql
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriterTest.kt
These are no longer needed now that Cloud Spanner has native protobuf support.
> refactor: Drop JSON debugging columns from Kingdom Spanner DB

- src/main/terraform/gcloud/cmms/.terraform.lock.hcl
- src/main/terraform/gcloud/cmms/versions.tf
- src/main/terraform/gcloud/examples/duchy/versions.tf
- src/main/terraform/gcloud/examples/kingdom/versions.tf
- src/main/terraform/gcloud/examples/simulators/versions.tf
- src/main/terraform/gcloud/modules/node-pool/main.tf
- src/main/terraform/gcloud/modules/node-pool/versions.tf
> fix: Disable insecure kubelet readonly port on GKE node pools

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FrequencyDistributionSubject.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FuzzyLongSubject.kt
- src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/MeasurementResultSubject.kt
These were introduced when the Truth version was upgraded in #1790.
> fix: Address compile warnings on custom Truth subjects

- .github/workflows/terraform-cmms.yml
- src/main/terraform/gcloud/examples/duchy/main.tf
- src/main/terraform/gcloud/examples/kingdom/main.tf
Different Halo test environments have different Spanner resource needs. For example, the `head` environment tends to have much lower traffic compared to the `qa` environment. Spanner autoscaling only supports whole nodes (multiples of 1000 processing units), whereas some test environments are often idle and do not need a whole node. Spanner nodes are relatively expensive (currently $657/month for the us-central1 region).
This also removes the specification of 100 processing nodes for the example Terraform configuration, as that is far below Spanner recommendations.
> ci: Read Spanner processing units from GitHub environment

- src/main/resources/kingdom/spanner/shard-measurements-by-continuation-token.sql
BREAKING CHANGE: This is updating an existing Liquibase changeset, and will therefore require manual adjustments wherever it has been rolled out. This should only have rolled out to Halo test environments.
Closes #1862
> fix!: Ensure that MeasurementIndexShardId is non-negative

- .github/workflows/scan-images.yml
Newer versions using caching for the vulnerability DB, which should reduce the likelihood of `TOOMANYREQUESTS` errors.
> ci: Update aquasecurity/trivy-action to 0.28.0

- .github/workflows/build-test.yml
- .github/workflows/configure-aws-duchy.yml
- .github/workflows/configure-duchy.yml
- .github/workflows/configure-kingdom.yml
- .github/workflows/configure-reporting-v2.yml
- .github/workflows/configure-reporting.yml
- .github/workflows/configure-simulators.yml
- .github/workflows/maybe-push-images.yml
- .github/workflows/publish-maven-artifacts.yml
- .github/workflows/push-images.yml
- .github/workflows/release-test.yml
- .github/workflows/run-k8s-tests.yml
- .github/workflows/update-cmms.yml
- src/main/docker/BUILD.bazel
- src/main/docker/macros.bzl
The `ci` Bazel configuration enables remote execution and caching via BuildBuddy. There was some missing configuration in #1840 which prevents the `update-cmms` workflow from completing successfully.
> fix: Ensure update-cmms workflow can run with ci Bazel configuration

- .github/workflows/scan-images.yml
- .github/workflows/update-trivy-cache.yml
See https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#updating-caches-in-the-default-branch
> ci: Keep Trivy cache up-to-date on default branch

- .github/workflows/update-trivy-cache.yml
The GitHub Actions cache version includes the path and does not disambiguate equivalent paths. Therefore the relative path `.cache/trivy-cache` results in a different version than the absolute path `/home/runner/work/cross-media-measurement/cross-media-measurement/.cache/trivy`.
Closes #1891
> ci: Fix cache path for update-trivy-cache workflow

- .github/workflows/build-test.yml
- .github/workflows/run-k8s-tests.yml
This should reduce the likelihood of having disconnections from the BuildBuddy Build Event Service (BES).
> ci: Set TCP keepalive for Bazel test workflows

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt
fix: Remove if check for update time filters when adding shard ID clause in StreamMeasurements
StreamMeasurements always orders results by Update time so the shard ID clause should always be added. [Testing](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1805) revealed that with the if check, setting the after field is required for it to work properly.
> fix: Remove if check for update time filters when adding shard ID clause in StreamMeasurements

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelRelease.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ModelReleasesServiceTest.kt
There is a bug where population is not added to the model release upon creation. This change fixes that bug by 1) including the population field when a new model release is created, 2) populating the externalDataProviderId(population data provider) and externalPopulationId fields when converting from external to internal model release, and 3) populating the population field when converting from internal to external model release.
> fix: Ensure population is persisted in ModelRelease upon creation

- MODULE.bazel
- MODULE.bazel.lock
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
> fix!: Update maximum and default page_size for ListRequisitions and ListEventGroups

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
The MC and EDP simulators were only reading the first page of results from ListEventGroups. This means that in environments with more EventGroups, not all test EventGroups would be read. This is exacerbated by #1916, as the default page size is now smaller.
> fix: Read all EventGroups from simulators rather than stopping at first page

- src/main/proto/wfa/measurement/access/v1alpha/principals_service.proto
- src/main/proto/wfa/measurement/access/v1alpha/role.proto
- src/main/proto/wfa/measurement/internal/access/principals_service.proto
The UpdatePrincipal method does not make sense as all the fields on Principal are immutable.
> fix: Drop unused UpdatePrincipal method and rename repeated field

- experimental/reporting-ui/src/main/react/reporting-ui/BUILD.bazel
This target can fail when built remotely, e.g. using BuildBuddy.
> ci: Mark webpack_bundle target as no-remote-exec

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/SyntheticGeneratorEdpSimulatorRunner.kt
This ensures that annotated event templates are found in the descriptor set passed to --event-message-descriptor-set
Closes #1934
> fix: Register event annotations when loading event message descriptor

- experimental/reporting-ui/src/main/kotlin/org/wfanet/measurement/reporting/bff/deploy/common/server/ReportingApiServerFlags.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessReportingServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/job/ReportSchedulingJobExecutor.kt
- src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/server/V2AlphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
Support VID Model Line rollout using Reporting Server flags. Two flags are added:
–default-vid-model-line=<String>
Specifies the VID model line value to be used for the “model_line” field in MeasurementSpec This in turn determines what VID model line that EDPs will use to fulfill Requisitions. If empty EDPs must agree offline what the default is. Once enabled we encourage that this case become an error.
–measurement-consumer-vid-model-line=Map<String, String>
A map of MC names to model lines. When a Metric is created, if the Metric is for an MC present in this map, then the model line provided as the value will be used for the  “model_line” field in MeasurementSpec.
> feat: Add flag for specifying the the VID model line

- src/main/k8s/dev/duchy_gke.cue
This option was intended to be set in #1707, but was missing on the GKE Duchy configuration.
> fix: Set --hmss-maximum-concurrency=5 in dev configuration for GKE

- .github/workflows/configure-reporting-v2.yml
- src/main/k8s/dev/BUILD.bazel
This addresses a build breakage for this target introduced in #1982, causing the nightly build to fail.
> fix: Pass spanner_instance var to Reporting v2 GKE deployment

- .github/workflows/update-cmms.yml
The K8s tests now cover the Reporting system, so the test job should wait for it to be updated.
> fix: Ensure that the run-tests job depends on the update-reporting-v2 job

- src/main/terraform/gcloud/cmms/reporting_v2.tf
- src/main/terraform/gcloud/examples/reporting/main.tf
As of #1982, Access is deployed in the Reporting cluster. This requires additional machine resources.
> fix: Increase Reporting cluster resources for Access

- src/main/k8s/testing/secretfiles/reporting_secrets_kustomization.yaml
> fix: Add missing reporting_root.pem to Reporting secret

- src/main/k8s/dev/reporting_v2_gke.cue
> fix: Specify K8s ServiceAccount for internal Access Deployment

- src/main/k8s/testing/secretfiles/amazon_edp_root_old.pem
After the API resources are updated, the AKID mapping config for Halo QA can be changed.
> chore: Add new Amazon EDP root cert for Halo QA

- src/main/kotlin/org/wfanet/measurement/integration/common/reporting/v2/InProcessLifeOfAReportIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
In the integration tests, the expected reach and frequency should be calculated from the full set of vids (filtered by the requsition's eventGroupSpecs).
> fix: Integration tests support fractional sampling widths.

- src/main/kotlin/org/wfanet/measurement/access/common/TlsClientPrincipalMapping.kt
- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPermissionsService.kt
This ensures that callers using mTLS auth can still call the proxied DataProviders and EventGroupMetadataDescriptors services.
Replaces #2024
> fix: Ensure TlsClient principals grant access to root resource 

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaultsTest.kt
> fix: Stop throwing error when random_start in MetricSpecConfig is valid

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt
From testing on halo-cmm-dev, we see that ListRequisitions filtering by Measurement State and Requisition State results in a full table scan of the Measurements table. This is the exact call used by EDP simulators once per second.
In addition to making the query itself slow, this can result in locking all Measurement rows. This in turn can result in long lock waits for writes to the Measurements table.
> perf: Avoid full table scan of Measurements in Requisitions query

- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationSpecConverter.kt
Reverts world-federation-of-advertisers/cross-media-measurement#2036
This breaks the EDP simulator when using other event templates (i.e. not Halo test templates).
> Revert "fix: Update population spec converter"

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FulfillRequisition.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This should avoid a full scan of the Requisitions table when fulfilling a Requisition via a Duchy.
> perf: Force index when reading Requisition by ExternalComputationId

- src/main/kotlin/org/wfanet/measurement/access/deploy/tools/Access.kt
- src/test/kotlin/org/wfanet/measurement/access/deploy/tools/AccessTest.kt
* Explicitly specify required/optional for each flag
* If a command only has one param, then use implement it as a positional param.
* Add missing DeleteRole CLI and test.
* Add id field to CreatePolicy
* Reuse policy binding ArgGroup in PolicyBindingChangeFlags
> fix: fix various mistakes and errors in access cli

- src/main/cc/wfa/panelmatch/common/crypto/BUILD.bazel
- src/main/cc/wfa/panelmatch/common/crypto/random_bytes_key_generator.cc
This prepares for Tink 3.0.
SecretData will become a container which can only be manipulated in Bulk. See https://github.com/tink-crypto/tink-cc/blob/main/tink/util/secret_data_internal_class.h for the API.
Unfortunately it is a little bit difficult for me as Tink maintainer to deprecate these functions since currently SecretData is an alias for std::vector<uint8_t, SecretAllocator>. This will however change.
> chore: Avoid changing individual bytes in SecretData

- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/InternalApiServices.kt
- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPoliciesService.kt
- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPrincipalsService.kt
- src/main/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerRolesService.kt
- src/main/kotlin/org/wfanet/measurement/access/service/internal/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/access/service/internal/testing/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/access/service/internal/testing/PermissionsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/access/service/internal/testing/PoliciesServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/access/service/internal/testing/PrincipalsServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/access/service/internal/testing/RolesServiceTest.kt
- src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/IdGenerator.kt
- src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPermissionsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPoliciesServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerPrincipalsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/access/deploy/gcloud/spanner/SpannerRolesServiceTest.kt
This will be used by the Basic Reports API.
> refactor: Move the new ID Generator out of access and into common

- docs/operations/updating-release.md
* Drop mention of updating from pre-0.1.0.
* Explicitly recommend keeping Kubernetes object configurations under version control.
* Use latest version in example.
* Clarify usage of `--prune` option for kubectl.
> docs: Update the release update guide

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
The field is currently not populated in this situation.
> fix: Set cmmsMeasurements in MetricResult when Metric fails

- src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt
- src/main/kotlin/org/wfanet/measurement/common/api/grpc/ListResources.kt
- src/main/kotlin/org/wfanet/measurement/edpaggregator/requisitionfetcher/RequisitionFetcher.kt
- src/main/kotlin/org/wfanet/measurement/integration/common/InProcessMeasurementSystemProberIntegrationTest.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt
- src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt
- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt
- src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt
These are used by internal APIs instead of string tokens.
> refactor: Update ListResources to handle protobuf message page tokens

- src/main/python/wfa/measurement/reporting/postprocessing/tools/post_process_origin_report.py
In the report post-processing program, when parsing unique reach measurements, e.g. reach(X - Y), sometimes we need to infer the measurement reach(Y) from reach(X - Y) and reach (X union Y). This involves computing the variance of the measurement reach(Y). 
Previously, it was assumed that reach(X - Y) is computed directly from reach(Y) and reach(X union Y), however, this does not seem to be true (e.g. it is computed from primitive regions instead).
A temporary solution is to use the maximum of the variance of reach(X - Y) and reach(X union Y) for reach(Y). This is expected to not have much effect on the output of the report processor program.
> fix: Use approximated variance for measurements derived from the unique reach ones.

- .github/workflows/build-test.yml
- MODULE.bazel
- requirements.txt
- src/test/python/wfa/measurement/reporting/postprocessing/tools/BUILD.bazel
All Python tests work fine with bazel test, but [this test](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/python/wfa/measurement/reporting/postprocessing/tools/test_post_process_origin_report.py) fails with bazel coverage because it cannot find the protobuf dependency:
```
from google.protobuf.json_format import Parse
ModuleNotFoundError: No module named 'google'
```
It seems that bazel test and bazel coverage handle the PYTHONPATH differently.
**bazel test adds:**
```
.../protobuf~
.../protobuf~/python (where the protobuf library is, with the structure that the test expects)
.../protobuf~/python/python
and directories like:
/rules_pythonpip~pip_311_<<dependency declared in the requirements.txt>>
/rules_pythonpip~pip_311_<<dependency …
```
> build: Add python test coverage report

- .github/workflows/attach-clis-to-release.yml
GitHub workflow that builds CLIs and attaches them to a GitHub release, triggered on creation of the release
> build: attach CLI uber jars to new releases

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsService.kt
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ReportsServiceTest.kt
If Report creation fails before Metrics are created, the Report ends up in a broken state. If creation is retried, it will be fixed. If not, the Report will be missing Metrics. This sets the Report to FAILED when Metrics are missing.
> fix: Missing Metrics no longer cause a problem when retrieving Reports

- docs/gke/reporting-v2-server-deployment.md
Options to the internal server were being conflated with build variables in #2125.
> docs: Fix Reporting deployment guide w.r.t. BasicReports

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt
- src/main/proto/wfa/measurement/reporting/v2alpha/BUILD.bazel
- src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsServiceTest.kt
This plumbs through the corresponding field from the CMMS API.
> feat: Add data_availability_interval to Reporting EventGroup

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
RequistionsService incorrectly throws an error when `DuchyValue` doesn't have the `protocol` field specified, in cases where it may be expected to be absent. For example, if a Measurement is cancelled before the Duchy sets its requisition params.
> fix: filter out no-protocol duchy in requisition conversion from internal to public

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt
- src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel
- src/main/proto/wfa/measurement/internal/kingdom/event_group.proto
- src/main/proto/wfa/measurement/internal/kingdom/event_group_details.proto
- src/main/resources/kingdom/spanner/add-event-group-data-availability.sql
- src/main/resources/kingdom/spanner/changelog.yaml
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
This moves persistence of EventGroup.data_availability_interval from EventGroupDetails to DB columns of type TIMESTAMP. Doing so allows for comparison operators in queries, which is necessary for #2124. This results in data loss of existing data availability values, which should be fine as the field is not yet being used.
BREAKING CHANGE: Any existing EventGroup data availability intervals will be lost
> feat!: Persist EventGroup data availability interval in DB columns

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
A failure reason enum is added to differentiate between a Measurement Result having issues and a Measurement itself in a FAILED state.
> refactor: Metric State is set to FAILED when Measurement Result issues are present

- src/main/kotlin/org/wfanet/measurement/securecomputation/controlplane/v1alpha/WorkItemAttemptsService.kt
- src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/spanner/SpannerWorkItemService.kt
- src/main/kotlin/org/wfanet/measurement/securecomputation/service/internal/testing/WorkItemsServiceTest.kt
- src/test/kotlin/org/wfanet/measurement/securecomputation/controlplane/v1alpha/WorkItemAttemptsServiceTest.kt
Fixes two issues:
1. Creation of internal work item attempts from public api
2. Publishes messages of type WorkItem, not WorkItemParams on internal api
> Fix: Secure Computation Work Item Attempts Service

- .codecov.yml
Disable the posting of Codecov comments on the PRs to reduce the noise caused by not having Kotlin test coverage yet.
It only disables the posting of the comment; the calculation, upload, and integration of the coverage reports still work.
> ci: Disable Codecov comment in PRs

- src/main/proto/wfa/measurement/edpaggregator/v1alpha/results_fulfiller_params.proto
The Data Provider Name is needed to properly construct the mtls channel from the TEE to the Kindom with principal name of the EDP.
> add data provider to result fulfiller params

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/EventGroupsService.kt
- src/main/proto/wfa/measurement/reporting/v2alpha/BUILD.bazel
- src/main/proto/wfa/measurement/reporting/v2alpha/event_groups_service.proto
This only updates the API definition. If either of the new request fields is specified, the RPC will result in an UNIMPLEMENTED status.
> feat: Add structured filter criteria to Reporting ListEventGroups

- .github/workflows/scan-images.yml
This fixes the error of 'unable to find image postgres-internal-server' in scan-images during Update CMMS ([example](https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/14869273851/job/41754019619)), similar to #2208. The image was renamed in #2097.
> fix: Update reporting internal server image name in scan-images.yml

- .github/workflows/scan-images.yml
This fixes the error of 'no such image' in scan-images during nightly build's Update CMMS ([example](https://github.com/world-federation-of-advertisers/cross-media-measurement/actions/runs/14900351812/job/41850981649)), similar to https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/2208 and https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/2277. The image was added in https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/2144.
> fix: update secure-computation image names

- src/main/terraform/gcloud/cmms/main.tf
- src/main/terraform/gcloud/examples/kingdom/main.tf
The schema updates in #2278 require this edition as they use the full-text search feature.
> fix: Specify ENTERPRISE edition for Spanner instance

- tools/integer-ids/external-to-api
This prevents getting the wrong number of bytes in the output (e.g. 7 instead of 8).
> fix: Pad hex representation of integer ID to 16 hex digits instead of 8

- src/main/kotlin/org/wfanet/measurement/dataprovider/RequisitionFulfiller.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerRequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamRequisitions.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/RequisitionReader.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt
- src/main/proto/wfa/measurement/api/v2alpha/page_token.proto
- src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt
This applies when listing by DataProvider parent. It should prevent scanning more rows on the Measurements table than the specified limit.
Closes #2299
BREAKING CHANGE: `measurement_states` is no longer supported in `ListRequisitionsRequest.Filter` except in the case where it's set to `AWAITING_REQUISITION_FULFILLMENT` when `states` is set to `UNFULFILLED`. This is the only observed call pattern, in which case `measurement_states` is actually redundant.
BREAKING CHANGE: `ListRequistions` now depends on Requisitions being in the `WITHDRAWN` state under the appropriate conditions. There must not be any `UNFULFILLED` Requisitions in the system created by versions prior to v0.5.9.
> perf!: Apply limit before joining Requisitions to Measurements

- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt
- src/main/proto/wfa/measurement/reporting/v2alpha/permissions_config.textproto
- src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt
invalidateMetric was looking for the reporting.metrics.create permission.
> fix: Add reporting.metrics.invalidate permission for invalidateMetric

- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelRolloutsServiceTest.kt
The performance issue introduced in #1076 was addressed in #2353 by applying a limit to the readLatestModelRolloutData query.
Closes #1368
> test: Re-enable SpannerModelRolloutsServiceTest

- src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/common/api/grpc/AkidPrincipalServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/grpc/Interceptors.kt
- src/main/kotlin/org/wfanet/measurement/common/grpc/PrincipalRateLimitingServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/common/identity/AuthorityKeyServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt
- src/main/kotlin/org/wfanet/measurement/common/ratelimit/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/common/ratelimit/RateLimiter.kt
- src/main/kotlin/org/wfanet/measurement/common/ratelimit/TokenBucket.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/AccountAuthenticationServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ApiKeyAuthenticationServerInterceptor.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel
- src/main/proto/google/longrunning/BUILD.bazel
- src/main/proto/wfa/measurement/config/BUILD.bazel
- src/main/proto/wfa/measurement/config/rate_limit_config.proto
- src/test/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/common/grpc/PrincipalRateLimitingServerInterceptorTest.kt
- src/test/kotlin/org/wfanet/measurement/common/ratelimit/BUILD.bazel
- src/test/kotlin/org/wfanet/measurement/common/ratelimit/TokenBucketTest.kt
RELNOTES: The Kingdom public API server now supports rate limiting. This can be configured using the `--rate-limit-config-file` option. The rate limit is applied individually for each server instance and each client certificate authority key identifier.
Closes #2312
> feat: Support RPC rate limiting for Kingdom public API services

- src/main/terraform/gcloud/cmms/edp_aggregator.tf
- src/main/terraform/gcloud/modules/edp-aggregator/main.tf
- src/main/terraform/gcloud/modules/edp-aggregator/variables.tf
The Event Group Sync Cloud Function is deployed via the `deploy_edp_aggregator_cloud_functions` workflow using a gcloud command.
Terraform was previously attempting to assign the `roles/run.invoker `permission to the Data Watcher service account for this function, but failed because the function does not yet exist at the time of the Terraform run.
This PR removes the IAM binding from Terraform to prevent the failure. The binding will be applied separately using a gcloud command in a follow-up PR.
> fix: remove event group sync iam binding

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/server/SpannerKingdomDataServer.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataServices.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/main/proto/wfa/measurement/internal/kingdom/event_groups_service.proto
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
RELNOTES: The Kingdom internal API server has a new `--max-event-group-read-staleness` option that can be used to configure the maximum staleness for stale reads of EventGroups.
> perf: Use stale reads for ListEventGroups

- src/main/k8s/dev/duchy_gke.cue
OOMKilled events were still observed despite the changes in #2558. After reviewing monitoring, it appears that the max heap size is set much higher than necessary. This means that the container memory limit can also be reverted back to 512 MiB.
RELNOTES: Operators will likely want to decrease the max heap size of the Duchy computation control service to 192MiB to accomodate dependency updates.
> fix: Reduce max heap size of computation control server

- src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt
- src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsServiceTest.kt
The comparison was incorrectly trying to compare internal vs. public MediaType.
Issue: #2613
> fix: Compare public API MediaType in ListEventGroups page token

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt
This reduces the chance of a full table scan and allows indexing.
Issue: #2536
> perf: Drop CTE for EventGroupMediaTypes

- src/main/terraform/gcloud/modules/gcs-bucket-cloud-function/main.tf
- src/main/terraform/gcloud/modules/http-cloud-function/main.tf
Reverts #2636
Nightly build is broken because it's missing some IAM setup in the terraform step.
> Revert "fix: add set no allow unauthenticated (#2636)"

- src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/BUILD.bazel
This fixes the libc++ error in the release test workflow. See #2562
> test: Ensure GCloudSpannerInProcessReachMeasurementAccuracyTest runs locally

- .github/actions/install-otel-operator/action.yml
- docs/gke/metrics-deployment.md
- src/main/k8s/open_telemetry.cue
Issue: #2701
RELNOTES: Operators may want to update their OpenTelemetry Operator to at least v0.129.1 with CertManager v1.18.2 and Auto Instrumentation Java v2.18.1.
> chore: Update OpenTelemetry Operator to 0.129.1

- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/tools/BUILD.bazel
- src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/tools/CopyEventGroups.kt
- src/main/resources/kingdom/spanner/add-event-groups-copy.sql
- src/main/resources/kingdom/spanner/changelog.yaml
- src/main/resources/kingdom/spanner/swap-event-groups.sql
Issue: #2536
RELNOTES: This update includes a data migration of the EventGroups table. The update must be applied while there is no traffic to that table. It is highly recommended to back up the Kingdom database before applying this update.
> perf: Un-interleave EventGroups table

- .github/workflows/maybe-push-images.yml
Issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/2211
> chore: Rename GH vars used for test signed builds

- src/main/kotlin/org/wfanet/measurement/computation/KAnonymityParams.kt
- src/main/kotlin/org/wfanet/measurement/computation/ReachAndFrequencyComputations.kt
- src/main/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/compute/protocols/direct/DirectReachResultBuilder.kt
- src/main/kotlin/org/wfanet/measurement/eventdataprovider/requisition/v2alpha/common/FrequencyVectorBuilder.kt
- src/test/kotlin/org/wfanet/measurement/computation/ReachAndFrequencyComputationsTest.kt
- src/test/kotlin/org/wfanet/measurement/edpaggregator/resultsfulfiller/compute/protocols/direct/DirectReachResultBuilderTest.kt
Two variables were being used to track max frequency for reach calculation use cases with k-anonymity is applied. This PR makes reachMaxFrequencyPerUser a required k-anonymity param and replaces the existing maxFrequency param in the DirectReachResultBuilder.
> combine DirectReachResultBuilder maxFrequency with KAnonymity.reachMaxFrequencyPerUser

- src/main/kotlin/org/wfanet/measurement/edpaggregator/requisitionfetcher/RequisitionGrouperByReportId.kt
- src/main/kotlin/org/wfanet/measurement/edpaggregator/requisitionfetcher/testing/TestRequisitionData.kt
- src/test/kotlin/org/wfanet/measurement/edpaggregator/requisitionfetcher/RequisitionGrouperByReportIdTest.kt
This fixes a bug where the model line was not properly set by GroupRequistionByReportId.
> bug: set model line in grouped requisitions by report id

- src/main/proto/wfa/measurement/reporting/postprocessing/v2alpha/report_post_processor_result.proto
- src/main/python/wfa/measurement/reporting/postprocessing/report/report.py
- src/test/python/wfa/measurement/reporting/postprocessing/report/report_test.py
Sometimes, noise correction makes large adjustments to the measurement values. This PR adds these measurements with relevant information to the ReportPostProcessorResult, which is included in ReportPostProcessorLog. The additional information will help users identify potential issues, either with the input report, or with the noise correction result.
> feat(report-processor): Log when a Measurement has a large correction
